### ISSUE TITLE
Need to rename transaction to batch in http and gRPC endpoints. 

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#101]
The transaction support we have added works more like a batch. Let's make that more explicit. This will require us refactoring:
- The https endpoint (url)
- The gRPC rpc name.
- The CRUD interface in `crud.go` and `operations.go`
- the func name in sql and mongo packages

**Comment by Jayesh333** [comment]
Here's how the batch API should look for javascript:
```js
const batch = db.beginBatch();
batch.add(db.insert(col).docs(...docs));
batch.add(db.update(col).where(whereClause).set())

// Apply batch
batch.apply().then(res => ...).catch(ex => ...)
```
Same can be ported to other client libraries as well

**Comment by KhushalPShah** [comment]
Have done the refactoring and have created a Pull Request.
