### ISSUE TITLE
Provide a means to refresh table from a specific table

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1013]
We only have a button to refresh the entire database schema. This option isn't available for a single table though. We have an API to do this but not exposed via. mission control

**Comment by sharadregoti** [comment]
@HeyItsJs can you add the support for this in the frontend

**Comment by HeyItsJs** [comment]
Yes

**Comment by HeyItsJs** [comment]
Dine. Coming in `v0.19.0`
