### ISSUE TITLE
Add space-cli commands to view, change and delete accounts

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1021]
We need the following commands
- `space-cli accounts view` -> This should list all the accounts. The keys should be replaces by `*`s. We can have an optional `--show-keys` flags which displays the keys as well. We can optionally pass an argument (account id) which displays only the account provided

- `space-cli accounts set <id>` -> this will set the provided account as the selected account if it exists.

- `space-cli accounts delete <id>` -> This will delete the provided account if it exists.

**Comment by YourTechBud** [comment]
@HeyItsJs how should the edit command look like?

**Comment by sharadregoti** [comment]
fixed in #1024
