### ISSUE TITLE
Provide a feature to configure database driver config

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1023]
### The problem faced currently?
No way to configure the underlying database drivers
### How can we solve it?
We should expose this on the frontend.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
What type of config are we talking about here? Things like connection pooling?

**Comment by YourTechBud** [comment]
Yes @HeyItsJs. Done in the backend.

**Comment by HeyItsJs** [comment]
Done in frontend as well
