### ISSUE TITLE
Sort operations is incorrectly shown in docs example

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1040]
On multiple operations page:
https://docs.spaceuptech.com/storage/database/queries/multiple-operations/
**Sort query is incorrectly shown, it should be ["name"]**
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Fixed. Made live.
