### ISSUE TITLE
the Upgrade to Space Cloud Pro is avaliable！！

### ISSUE THREAD

**Issue by zhangyan1298** [spaceuptech/space-cloud#1041]
the Upgrade to Space Cloud Pro is avaliable！

i use space cloud miss-control opensource v0.17.0

when i chick https://console.spaceuptech.com/mission-control respone 
is error page

**Comment by YourTechBud** [comment]
Hey. We haven't released the pro version yet. Also where did you get that link? It doesn't really exist.

We should be releasing the pro version around this weekend. I'll update you here once it's out.

**Comment by zhangyan1298** [comment]
thks! How to configure persistent data with open source version v0.17
Now there is a problem. Every time the container is restarted, the previously configured data will be lost

**Comment by YourTechBud** [comment]
Make sure you install SC using this guide: https://docs.spaceuptech.com/install/

**Comment by YourTechBud** [comment]
The enterprise version of Space Cloud has been officially released!

Visit https://console.spaceuptech.com for more details.
