### ISSUE TITLE
Support headers for accessing the Remote Services

### ISSUE THREAD

**Issue by waynesi** [spaceuptech/space-cloud#1067]
### The problem faced currently?

It's great that we can convert RESTful Web API to GraphQL. However, when accessing the Remote Services, quite often we need to provide some security secrets along with our requests. In my case, I need to include a couple of HTTP headers, but I couldn't find any way to do it.

### How can we solve it?

Please allow specifying HTTP headers as part of the Remote Service setting or Per Endpoint setting, just like what we can do on Postman. Thanks.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Hey, @waynesi Thanks for the feature request! That's actually a very valid use case. Implemented this in the `v0.18.0` (about to be released in a day).

**Comment by HeyItsJs** [comment]
To be clear, we will be allowing this on a per endpoint level. @waynesi

**Comment by waynesi** [comment]
That's really great news. Thanks a lot for the update and super quick turnaround. Much appreciated!

**Comment by YourTechBud** [comment]
Done. Coming in `0.18.0`

**Comment by waynesi** [comment]
Sorry. I've just pulled down 0.18.0 but I can't see where to add the headers?

**Comment by YourTechBud** [comment]
Head over to remote services. Open up an `endpoint`. You should be able to see the `headers` config in the advanced config.

If you can't see it there, make sure you delete mission-control from `$HOME/.space-cloud` directory or refresh with cache disabled to see the latest mission control

**Comment by waynesi** [comment]
Thanks a lot. After destroying the environment and deleting the .space-cloud folder, I can see the new options now. Brilliant. Thanks.

**Comment by YourTechBud** [comment]
We'll update the docs soon enough for this. Meanwhile, feel free to reach out on Discord if you need help.
