### ISSUE TITLE
EOF error when chaining endpoints

### ISSUE THREAD

**Issue by waynesi** [spaceuptech/space-cloud#1073]
Hi,

I defined two RESTful endpoints under the same Remote Service and tried to chain them together, but I ended up with EOF error although each endpoints worked fine and can even be nested as long as I don't use parameters to chain them.

My endpoints configuration is
```
Remote Service Name: ctapi
Endpoint 1 Name: events, Path: events
Endpoint 2 Name: attendance, Path: attendance?eventId={args.id}
```

Run the `events` endpoint alone
```
query {
  events @ctapi {
    id
  }
}
```
, and I got 
```
{
  "data": {
    "events": [
      {
        "id": 98
      },
      {
        "id": 103
      }
    ]
  }
}
```

Run the `attendance` endpoint alone
```
query {
  attendance(id:103) @ctapi {
    source
  }
}
```
, and I got
```
{
  "data": {
    "attendance": [
      {
        "source": "R"
      },
      {
        "source": null
      },
      {
        "source": "M"
      }
    ]
  }
}
```

Running both endpoints nested but not chained
```
query {
  events @ctapi {
    attendance(id:103) @ctapi {
      source
    }
  }
}
```
, and I got
```
{
  "data": {
    "events": [
      {
        "attendance": [
          {
            "source": "R"
          },
          {
            "source": null
          },
          {
            "source": "M"
          }
        ]
      },
      {
        "attendance": [
          {
            "source": "R"
          },
          {
            "source": null
          },
          {
            "source": "M"
          }
        ]
      }
    ]
  }
}
```
But when I run chained
```
query {
  events @ctapi {
    attendance(id:"events.id") @ctapi {
      source
    }
  }
}
```
, I ended up with 
```
{
  "errors": [
    {
      "message": "EOF"
    }
  ]
}
```

What's wrong please?

**Comment by HeyItsJs** [comment]
Hey @waynesi Can you confirm that the `attendance` endpoint doesn't throw an error for the other `event.id` (98)?

Seems like there might be a problem with the `attendance` endpoint. 

To reproduce what you said, I made the following service:
Remote Service Name : `myservice` Remote Service URL : `https://httpbin.org`
Endpoint 1 Name : `post` path: `/post`
Endpoint 2 Name: `post2` path: `/post?arg1={args.k1}`

> Note: https://httpbin.org is an online service that just sends the details of HTTP request (like args, body, headers, etc) back in the response

Then I made the following chained request (`k1` is taken from `post.json.k1`):
```graphql
{
  post(foo: "bar", k1: "somekey") @myservice {
    post2(k1: "post.json.k1") @myservice {
      args
      json
    }
  }
}
```

And I got the following response:
```graphql
{
  "data": {
    "post": {
      "post2": {
        "args": {
          "arg1": "somekey"
        },
        "json": {
          "k1": "somekey"
        }
      }
    }
  }
}
```

Also can you see if there's anything helpful in the logs of `space-cloud-gateway`?

**Comment by waynesi** [comment]
Hi @HeyItsJs,

Thanks a lot for your very timely reply. Much appreciated. You're right, the `attendance` endpoint doesn't always have data for all the possible event ids. When I tried with such event id on the nested but but not chained query, I ended up with the same EOF error.

However, our `attendance` endpoint does return proper 204 No Content status code which according to HTTP protocol is a succeeded response rather than an error. Is there any chance the space-cloud gateway can be improve to handle such situation more gracefully?

What we're trying to do is to build a GraphQL layer in front of our Web API layer, in order to avoid very verbose and chatty Web API calls from the client perspective. So basically we want the GraphQL layer to "join" the results of several Web API calls. But if the whole GraphQL query will simply fail because one nested Web API calls returns nothing, I'm afraid the practicality of your great feature is significantly limited. In my case, if the nested Web API call fails or returns nothing, I would like to see a `null` value instead. Maybe an advanced option can be provided for either fail-fast (the current behaviour) or use `null`.

Once again, thanks a lot for your help. Your fast turnaround and the level of help are very impressive. I'm sure your business will flourish.

**Comment by HeyItsJs** [comment]
Hey @waynesi, Thanks for the kind words! Words like this keep us motivated!

You have pointed a very valid point for the status code `204`. If the status code is `204`, then we can send `null` instead of trying to pare the response from the remote endpoint. 

This is an easy fix. you can expect it to be fixed it in a patch version soon. Closing this issue. Have created a separate specific issue for the same - #1077 to track this problem.

Thanks for bringing such use cases! It would be great if you can join the community discord channel of Space Cloud as well 😄 - https://discord.com/invite/RkGjW93

**Comment by waynesi** [comment]
Re: Discord. Thanks for the invite. Now downloading. Man, you have no idea how many comm apps I've installed since I joined Github 😂
