### ISSUE TITLE
EOF error when querying a remote service that returns 204 status code 

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1077]
If a remote service sends `204` status code, then space cloud shouldn't try to parse its response and instead return `null` for it in the GraphQL response.

Right now Space Cloud tries to parse that content which results in `EOF` since it's empty (which is valid because it's 204`)

This is a very easy fix and can be released in a patch as soon as possible. 

Meanwhile, let's check and fix if this same case is with event triggers webhook as well.  

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment]
Fixed in #1085
