### ISSUE TITLE
mission control throws error when second service is deployed

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1080]
### Describe the bug
My first service is httpbin. It gets deployed successfully but when I deploy another service mission control throws error.
![image](https://user-images.githubusercontent.com/24411676/84591554-f2166680-ae5c-11ea-9be0-50095bc07044.png)

### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.18.1`
