### ISSUE TITLE
Use pod domains instead of ip addresses in syncman/store_kube.go

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1083]
Currently when we watch services in `store_kube.go`, we extract the pods ip address instead of the pods domain name. Since we have domains available, we can use domains like `gateway-0.gateway.space-cloud.svc.cluster.local`.

Once this is done, we will have to test if the realtime module still works by connecting two clients on two different gateways.

**Comment by sharadregoti** [comment]
fixed in #1094
