### ISSUE TITLE
The service upstream config throws an error when a value other than * is used

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1084]
### Describe the bug
Istio throws an error when an upstream other than * is used. It says only full qualified domains are allowed. This is thrown when we apply the `Sidecar` config
### Expected behaviour
There should be no error.
### Actual behaviour 
There is an error
### Steps to reproduce
Apply a service with an upstream service other than `*`
### Your environment
- Space Cloud version: v0.18.0
- OS: Windows
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment]
fixed in #1094
