### ISSUE TITLE
Space cli fails when trying to apply a secret which already exists

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1086]
### Describe the bug
Space cli fails when trying to apply a secret which already exists. The error happens even when the exact same secret is being applied.

### Expected behaviour
The secret should be applied
### Actual behaviour 
Get an error message
`ERRO[0001] error while applying service got http status code 500 Internal Server Error - secret already exists type mismatch`
### Steps to reproduce
Create a secret via mission-control. Get the entire config using `space-cli get all --project <project-name> sc-config`. Then try to apply the secret file `space-cli apply sc-config/12-secrets.yaml`. You'll get the error.
### Your environment
- Space Cloud version: v0.18.0
- OS: Mac
- Docker / Kubernetes: Kubernetes
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment]
fixed in #1094
