### ISSUE TITLE
'space-cli setup' does not clean up after encountering error-state

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cloud#1090]
### The problem faced currently?
When the command `space-cli setup` encounters an error state while setting things up, the container `space-cloud-gateway`  and the network `space-cloud` might have already been created and are not removed. This behaviour leads to errors when trying to setup SpaceCloud in further iterations. Two encountered errors can be found below.

`ERRO[0000] Container (space-cloud-gateway) already exists  error=`

`ERRO[0000] Unable to start container (space-cloud-gateway)  error="Error response from daemon: network space-cloud is ambiguous (6 matches found on name)"`

### How can we solve it?
A possible solution to this problem would be to run `docker network rm space-cloud` and `docker rm space-cloud-gateway `when encountering an error-state. The side-effects of this have to be checked first, however.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by sharadregoti** [comment]
This will be solved in #1026
