### ISSUE TITLE
Custom events are not working

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1095]
### Describe the bug

Custom events are neither delivered to target nor persisted in the database.

### Expected behaviour
Custom events should get persisted in database and be delivered to the configured target.

### Actual behaviour 
Custom events are neither delivered to target nor persisted in the database.

### Steps to reproduce
Create a custom event with the following config in Mission Control:

```json
{
  "type": "myType",
  "url": "https://httpbin.org/post",
  "retries": 3,
  "timeout": 5000
}
```
Then queue an event to that event type from Mission Control itself in the `synchronous` mode. You will get error: `context deadline exceeded`.

Then queue the event in `asynchronous` mode. It will get queued. But then if you query `event_logs` table from the API explorer, you won't get any rows.

### Your environment
- Space Cloud version: v0.18.0
- OS: Linux
- Kubernetes or Docker: None. Using gateway binary directly

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by KavishShah09** [comment]
I was unable to reproduce this behavior @HeyItsJs

**Comment by sharadregoti** [comment]
@HeyItsJs what should we do about this issue ?

**Comment by HeyItsJs** [comment]
It's working for me as well now. Don't know why didn't it worked earlier. So closing this.
