### ISSUE TITLE
Add Auth0, Firebase Auth, AWS Cognito Support

### ISSUE THREAD

**Issue by narayandreamer** [spaceuptech/space-cloud#1112]
### The problem faced currently?

Add support for authentication like Auth0, Firebase Auth and AWS Cognito

### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
I suggest we add an independent user management module to this as well. This way those who don't want to you Oauth would be able to take advantage of this module as well.

**Comment by HeyItsJs** [comment]
As discussed in community call, we will be using JWK URLs to sync the secrets between space cloud and the identity providers. So basically In Mission Control, the user can add another type of secret (RSA JWK) to specify the JWK URL. (Note this secret can never be a primary secret)

**Comment by YourTechBud** [comment]
@HeyItsJs close this issue once you make the necessary changes in mission control.

**Comment by HeyItsJs** [comment]
Done in mission control!
