### ISSUE TITLE
we need a function to show the real query SQL and which step that cost .

### ISSUE THREAD

**Issue by pandaxxt** [spaceuptech/space-cloud#1120]
### The problem faced currently?
I run the GraphQL and use the sort to filter the result, for example: server( where: { pool: {_in: ["test"]}, decommission: {_eq: 0} }, sort: ["host_name"] ), this will cost almost 11s to get the result, but if i remove the sort: ["host_name"] ), the return will only 600ms.
### How can we solve it?
when there is the performance issue , we want to know the detail query in the graphQL. we need a function to show the real query and which step that cost .

**Comment by YourTechBud** [comment]
This is the SQL query analyzer we have been talking about

**Comment by sharadregoti** [comment]
Graphql query
```
query {
  users(debug:true) @mysql {
    id
    name
  }
  _query
}
```

Result

```
{
  "data": {
    "_query": [
      {
        "args": [
          1000
        ],
        "col": "users",
        "db": "mysql",
        "queryTime": "210.42µs",
        "sql": "SELECT * FROM users LIMIT ?"
      }
    ],
    "users": [
      {
        "id": "0bbacb5891c544f1b",
        "name": "Sharad Regoti"
      },
      {
        "id": "1mVhiUUFCXgjPX0PRgIifIxGKqB",
        "name": "SHARAD REGOTI"
      },
      {
        "id": "8989e865f4d841858",
        "name": "sharad regoti"
      }
    ]
  }
}
```
