### ISSUE TITLE
_regex does not support case insensitive query in mysql

### ISSUE THREAD

**Issue by ShubhankarKG** [spaceuptech/space-cloud#1121]
### Describe the bug

Our team uses mysql, and we needed to use case insensitive queries to search for regex patterns. We used the following query:
```graphql
{
  colleges (
    where: {name : {_regex: "frcrce"}}
  ) @mysql
}

```
This returned us an empty list.

```graphql
{
  colleges (
    where: {name : {_regex: "FRCRCE"}}
  ) @mysql
}
```
This worked correctly. 

Which implies that the query performed a case sensitive search.
### Expected behaviour
```graphql
{
 "data" : {
   "colleges" : [
          name:  "FRCRCE",
          # Other fields
     ]
   }
}
```

### Actual behaviour 
```graphql
{
 "data" : {
   "colleges" : [ ]
   }
}
```
### Steps to reproduce

Assume college name is in UPPERCASE. Then the regex match for smallcase should return an empty list as per the bug.

### Your environment
- Space Cloud version: 18.0
- OS: Ubuntu 18.04
- Kubernetes or Docker: Docker

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍 

I had to work on this so if this is indeed a bug, please let me know if there is a workaround also.

**Comment by HeyItsJs** [comment]
For the case-insensitive match, `(?i)` operator is to be used in the regex. But unfortunately, `(?i)` operator is supported by MySQL database for MySQL versions 8+ only. 

Two workarounds for MySQL versions lower than 8:
- Using `sort` in the query fixes this problem. Kind of weird. But it works.
- Use [prepared queries](https://docs.spaceuptech.com/storage/database/prepared-queries/)
