### ISSUE TITLE
Provide better hints when using space-cli generate incorrectly

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1127]
I used the following space-cli command to generate remote-services:

```bash
space-cli generate remote-services --project myproject
```

It gives me the following error:
```
ERRO[0000] incorrect number of arguments                
Error: incorrect number of arguments
```

As a next step that any developer would take, I ran the following command:
```bash
space-cli generate remote-services --help
```
And here's what I get 😐:
```bash
Usage:
  space-cli generate remote-services [flags]

Flags:
  -h, --help   help for remote-services

Global Flags:
      --log-level string   Sets the log level of the command (default "info")
      --project string     The project id to perform the options in
```   

This isn't really helpful. Ideally, the error message should have only said what argument it required in the first place. I this was some other tool, I would have dropped off at this point as I faced a roadblock which I couldn't solve.

**Comment by prakashmishra1598** [comment]
@YourTechBud , Can you assign this to me?

**Comment by YourTechBud** [comment]
This is done. Just done for the generate commands for not. We can creating another issue for doing the same with the `getters` #1153.

Closing this for now
