### ISSUE TITLE
_skip operation does not work for sql databases

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1131]
### Describe the bug
for limit operation we use OFFSET operator internally, but it throws error. As we cannot use OFFSET standalone. OFFSET should be used with limit
https://stackoverflow.com/questions/2827029/mysql-skip-first-10-results
### Your environment
- Space Cloud version:
- OS:
- Kubernetes or Docker:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Are you sure? @sharadregoti. As far as I remember, this used to work. 

Also you mentioned we are using OFFSET internally for limit. As far as I know, OFFSET should be used for skip and not limit. For limit, LIMIT is to be used.

**Comment by sharadregoti** [comment]
my bad it's _skip operation

**Comment by YourTechBud** [comment]
There is nothing we can do about it. Lets just mention this in the docs
