### ISSUE TITLE
Set a default project in space-cli

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1142]
### The problem faced currently?
most of the space-CLI commands require **--project** flag for proper functioning. This is really inconvenient sometimes. It would be great if we can set a default project.
### How can we solve it?
Add a command for setting default project to use if a project is not provided through --project flag.
Command : space-cli set default project "project-name-here"

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We can store this in the same accounts.yaml file which we use to store credentials

**Comment by thejasbabu** [comment]
Do you want to store this in accounts or config.yaml? Seems more like a config parameter

I can take this up

**Comment by YourTechBud** [comment]
Hey @thejasbabu. I think we should put it in the accounts.yaml file. @sharadregoti should we configure this on an account level or on global level?

**Comment by sharadregoti** [comment]
We should store this parameter at the account level. As space-CLI supports multiple clusters in v19. Each cluster is associated with an account. Switching account through space-CLI should also change the default project for that cluster/account.

**Comment by YourTechBud** [comment]
@thejasbabu should I assign this issue to you?

**Comment by YourTechBud** [comment]
Done by @sharadregoti
