### ISSUE TITLE
Add a space-cli delete <resource> command

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1155]
### The problem faced currently?
Currently we can apply config to SpaceCloud. This solves the need to create and update resources. However, there is no mechanism to delete a resource via. space-cli.
### How can we solve it?
We can add `deleters` for each resource. This will be similar to the `generators` and `getters`. We will have to be careful to make sure we give flexibility to delete resources by `id`, `prefix` (this can be a multi select) or delete all resources.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by KavishShah09** [comment]
I'm interested in taking this up

**Comment by sharadregoti** [comment]
Following resources are still pending
` secrets           
  service-role      
  service-routes    
  services          
`
