### ISSUE TITLE
Unable to create container (space-cloud-gateway)

### ISSUE THREAD

**Issue by JVariance** [spaceuptech/space-cloud#1157]
I follow along the official installation guide at https://learn.spaceuptech.com/space-cloud/basics/setup/
But when I use 'space-cli.exe setup --dev' I get following error.

`time="2020-07-13T11:30:13+02:00" level=info msg="Setting up Space Cloud on docker."
time="2020-07-13T11:30:13+02:00" level=info msg="Fetching latest Space Cloud Version"
time="2020-07-13T11:30:13+02:00" level=info msg="Starting container space-cloud-gateway..."
time="2020-07-13T11:30:13+02:00" level=info msg="Image spaceuptech/gateway:0.18.2 already exists. No need to pull it again"
time="2020-07-13T11:30:14+02:00" level=error msg="Unable to create container (space-cloud-gateway)" error="Error response from daemon: status code not OK but 500: {\"Message\":\"Unhandled exception: Filesharing has been cancelled\",\"StackTrace\":\"   bei Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\\\workspaces\\\\stable-2.3.x\\\\src\\\\github.com\\\\docker\\\\pinata\\\\win\\\\src\\\\Docker.ApiServices\\\\Mounting\\\\FileSharing.cs:Zeile 0.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\\\workspaces\\\\stable-2.3.x\\\\src\\\\github.com\\\\docker\\\\pinata\\\\win\\\\src\\\\Docker.ApiServices\\\\Mounting\\\\FileSharing.cs:Zeile 47.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\\\workspaces\\\\stable-2.3.x\\\\src\\\\github.com\\\\docker\\\\pinata\\\\win\\\\src\\\\Docker.HttpApi\\\\Controllers\\\\FilesharingController.cs:Zeile 21.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1'1.MoveNext()\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()\"}"`

- Space Cloud version: 0.18.2
- OS: Windows 10
- Kubernetes or Docker: Docker
- The client api version (if applicable):
- Browser (if applicable):

**Comment by YourTechBud** [comment]
The fix for this is coming in `v0.19.0`. Closing it for now.
