### ISSUE TITLE
space-cli should get secrets before database and file config

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1164]
`space-cli get all` gets all the resources and stores them in config files in a folder. These config files are names such that while applying the folder, the sequence is such that resources that have dependencies are applied later. For e.g. `12-secrets.yaml` and `13-services.yaml`.

However, we are keeping the `db-configs` and `filestorage-config` before the `secrets`. This might pose a problem if the database or file storage config is using a secret deployed by space cloud. So we should store secrets before these resources.

**Comment by sharadregoti** [comment]
@YourTechBud This is done in v0.19.0.
