### ISSUE TITLE
error applying secret in filestore config 

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1165]
### Describe the bug
I created a space cloud secret named for configuring GCP file store. But when I use that secret to configure file store, I get the following error:
```
dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: unexpected end of JSON input
```

The secret key name that I used was `serviceAccountKey.json`

The error got resolved when I changed the key name to `serviceAccountKey`

Seems, that space cloud is splitting by `.` and wasn't considering the `.json` from the `serviceAccountKey.json`. This shouldn't be the case though.

### Your environment
- Space Cloud version: `v0.18.3`
- OS: Linux
- Kubernetes or Docker: Docker
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Already done in `v0.19.3`
