### ISSUE TITLE
Create Contributor Guide

### ISSUE THREAD

**Issue by kaivalya97** [spaceuptech/space-cloud#1168]
### The problem faced currently?

New contributors need a go-to place for finding basic information about the project and tips on how to contribute. Today they ask questions on Discord or try to figure it out on their own.

### How can we solve it?

A contributor guide which lists general project practices, guidelines, and explaining the project structure.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done. Special thanks to @kaivalya97 and @prakashmishra1598!
