### ISSUE TITLE
Multiple projects

### ISSUE THREAD

**Issue by abasse** [spaceuptech/space-cloud#1176]
Hi guys,

I receive following error message when I try to create a second project:

_.."upgrade your plan to create more projects"_

What is the plan behind it? How can I run multiple projects?

Thanks,

André

**Comment by YourTechBud** [comment]
The ability to add multiple projects and databases will be introduced in the enterprise edition. The same is due to release at the end of this month.

**Comment by YourTechBud** [comment]
The enterprise version of Space Cloud has been officially released!

Visit https://console.spaceuptech.com for more details.
