### ISSUE TITLE
Cannot sort nested queries

### ISSUE THREAD

**Issue by mfouchi** [spaceuptech/space-cloud#1178]
### Problem:
Nested queries don't sort as stated in the docs:
[https://docs.spaceuptech.com/storage/database/queries/sorting/](https://docs.spaceuptech.com/storage/database/queries/sorting/) 
The root sorts just fine, but not the nested.  I'm attaching a file showing the 2 table types I'm using (user and post), the insert mutation with the data I'm using, and the query that isn't working. (it keeps returning them in ID order, which I guess is how they were inserted)  

### Steps to reproduce:
Tables:
```javascript
type user {
  id: ID! @primary
  name: String!
  posts: [Post] @link(table: "post", from: "id", to: "user_id")
}

type post {
  id: ID! @primary
  name: String!
  date_time: DateTime!
  user_id: ID @foreign(table: "user", field: "id")
}
```

Insert some data:
```javascript
mutation {
  insert_user(
    docs: [
     {
        id: "2"
        name: "User 2" 
    },
    {
        id: "1", 
        name: "User 1", 
        posts: [
          {
            id: "1"
            name: "March 1st"            
            date_time: "2020-03-01T20:00:00.000Z"
          },
          {
            id: "2"
            name: "March 3rd"
            date_time: "2020-03-03T20:00:00.000Z"
          },
          {
            id: "3"
            name: "March 2nd"
            date_time: "2020-03-02T20:00:00.000Z"
          }
        ]}]) @mysql {
    status
    error
    returning
  }
}
```

This query does not sort the posts properly.  It keeps returning them in ID order, which is how they were inserted
```javascript
{
  user(
    sort: ["name"]
  ) @mysql {
    id
    name
    posts(
    sort: ["name"]
  ) {
      id
      name
      date_time
    }
  }
}
```

### Your environment
- Space Cloud version: 0.18.4
- OS: Windows
- Docker:
- Browser (if applicable): Chrome

**Comment by mfouchi** [comment]
On Discord, YourTechBud suggested using an on-the-fly join, but that does not sort the nested query either:
`{ 
user( sort: ["name"] ) @mysql {
 id
 name
 posts( where:{user_id: "user.id"}, sort: ["name"] ) @mysql{
 id 
 name
 date_time
 }
 }`

**Comment by YourTechBud** [comment]
Done in `v0.20.0`
