### ISSUE TITLE
Add pagination for viewing logs of a service

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1183]
### The problem faced currently?
Currently, we can retrieve all the logs of a stream or stream the logs of a service. But what if a service is running for 1 month. We will get all the logs from the start.

### How can we solve it?
We can add pagination/filters saying we only want the latest logs or logs from this timestamp

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done in gateway

**Comment by HeyItsJs** [comment]
Done in Mission Control as well!
