### ISSUE TITLE
Add ability to provide length of var char when using type id

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1187]
Currently type ID is mapped to `varchar(50)`. This isn't suitable for all use cases.

We can add a `@size` directive which can be used to determine the size of `varchar`. Example:

```graphql
type users {
  id: ID @primary
  password: ID @size(value: 100)
}
```

This would create a table as follows:
```sql
create table users (
id varchar(50) primary key,
password varchar(100),
);
```

**Comment by HeyItsJs** [comment]
Coming in `v0.19.4`
