### ISSUE TITLE
AllRequest may be redundant

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#119]
Currently, `server.proto` defines `BatchRequest` in the following way: 
```
message AllRequest {
  string col = 1;
  bytes document = 2;
  string operation = 3;
  bytes find = 4;
  bytes update = 5;
  string type = 6;
}
message BatchRequest {
  repeated AllRequest batchrequest = 1;
  Meta meta = 2;
}
```

Instead of `AllRequest` we can directly use the already defined `CreateRequest`, `ReadRequest`, etc
```
message BatchRequest {
  repeated CreateRequest cr = 1;
  repeated ReadRequest rr = 2;
  repeated DeleteRequest dr = 3;
  repeated UpdateRequest ur = 4;
  repeated AggregateRequest ar = 5;
  Meta meta = 6;
}
```

To be considered:
1. This new method will remove the `AllRequest` message.
2. The predefined messages will be used. This will help to segregate and identify the specific components in the batch request. This may also make it easier to implement in the client modules.
3. The `meta` field may be repeated, but we can always omit it in the component `CreateRequest`, `ReadRequest`, etc.

**Comment by YourTechBud** [comment]
This does make sense. We should get this done before work starts on the client drivers. @Jayesh333 and @KhushalPShah what do you guys think about it?

**Comment by YourTechBud** [comment]
@AliabbasMerchant There is a problem with this. We'll loose the order of the requests. A batch must always be in order.

**Comment by AliabbasMerchant** [comment]
Oh. Ok

**Comment by YourTechBud** [comment]
I say we stick to the current implementation? Don't want to rush this through. It would be a breaking change otherwise. @KhushalPShah what do you think?

**Comment by KhushalPShah** [comment]
Yes, I guess lets keep things the way they are for now.
We can then keep on revising it to make it better if needed.

**Comment by KhushalPShah** [comment]
So can we close this issue?
As discussed, the main purpose for Ordering will be lost if we do not keep AllRequest.

**Comment by YourTechBud** [comment]
Yes. Let's close this
