### ISSUE TITLE
Add a claims field in endpoint config

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1194]
### The problem faced currently?
Currently we allow users to override the token in the incoming request of the `remote-services` module. This is not a good practice since the token can be easily compromised. 
### How can we solve it?
To overcome this, we should allow the user to set the claims instead and create the token with an expiration internally.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by KhushalPShah** [comment]
I am working on this.
Will raise a PR by 1st or 2nd of October.

**Comment by HeyItsJs** [comment]
Done in mission control.

**Comment by YourTechBud** [comment]
Done
