### ISSUE TITLE
Create a flag to disable Mission Control

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1196]
### The problem faced currently?
Currently gateway downloads and hosts mission control whether you want it or not. In many cases, a UI isn't required. Also, during local development, we host mission control locally.
### How can we solve it?
Create a flag `disable-ui` in gateway which stop SC from downloading or hosting mission control
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
So right now the gateway image that is distributed already has the Mission Control in it right? Correct me if I am wrong. So are we going to make the gateway container download the mission control now. Or are we going to have a separate mission-control-less gateway image and then the space-cli decides which image to pull based on the flag?

**Comment by HeyItsJs** [comment]
Or are we talking just about the gateway binary and not the docker image that is distributed?

**Comment by YourTechBud** [comment]
No. This is a gateway only config. The image we provide will always have the mission control assets

**Comment by YourTechBud** [comment]
Done
