### ISSUE TITLE
The docs are not in sync with the readme

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#120]
The docs do not have the motivation section present in the readme. Need to make sure they both are in sync.

**Comment by AliabbasMerchant** [comment]
Why don't we use some docs generation library like sphinx or something??  
We could use readme files and all to directly generate the docs website.

**Comment by AliabbasMerchant** [comment]
Why don't we use some docs generation library like sphinx or something??  
We could use readme files and all to directly generate the docs website.

**Comment by YourTechBud** [comment]
We are doing that right now. The entire docs is written in markdown! We have a node script which renders it into html!

The problem is that the entry point to the docs page and the readme file need to have slightly different content. That's where the problem is.

**Comment by AliabbasMerchant** [comment]
Oh. Ok
There is lots for me to discover in the project files and about how the project works 🙈

**Comment by YourTechBud** [comment]
Why don't we do this, lets make a contribution guide which also walks a person willing to contribute through the entire codebase and how its structured. How does this sound?

**Comment by YourTechBud** [comment]
They will be separate
