### ISSUE TITLE
Visualize JSON errors while editing security rules

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1203]
### The problem faced currently?
While editing security rules if some error occurs such as misplaced a "," or forgot one opening/closing bracket. We get the error when we click on the Save button. The notification only tells at which line the error has occurred.
### How can we solve it?
It would be great if Mission control highlights the errors while editing security rules in JSON. This feature is same as highlighting in VScode or similar IDE 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.20.0`
