### ISSUE TITLE
Space Cloud Gateway does not support kerberos authentication to Mongo

### ISSUE THREAD

**Issue by LECZYF** [spaceuptech/space-cloud#1207]
### The problem faced currently?
Space Cloud Gateway in its current form is not able to obtain kerberos ticket nor to use it to authenticate to Mongo. This makes it impossible to connect to Mongo instances secured by kerberos.

### How can we solve it?
- Install krb5 library in docker image
- Update the build process to include build tag mentioned in mongo go documentation: https://godoc.org/go.mongodb.org/mongo-driver/mongo#example-Connect--Kerberos

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@LECZYF is this feature blocking you from using SpaceCloud with Mongo? Is it possible to setup a proxy in the middle for now to skip the auth process for now?

**Comment by LECZYF** [comment]
Yes, this is a blocker and unfortunately it is impossible to setup such proxy in my use case. 
Are you aware of any issues that would block us from enabling this feature in gateway? Did you attempt to do so in the past?

**Comment by YourTechBud** [comment]
We can add this feature easily. @HeyItsJs Lets try to push this in `v0.19.1`

**Comment by LECZYF** [comment]
Sure, I could do this however I thought it could be beneficial for the project to give users possibility to use such auth mechanism if needed. The only permanent footprint on the gateway image would be this additional library and extended entrypoint with logic like "if KTAB_ENV set then run kinit".

Anyway, I was trying to experiment with enabling this on my own, could you please advise how should the build command look like considering:
_Using Kerberos authentication requires the "gssapi" build tag and cgo support during compilation._

**Comment by YourTechBud** [comment]
Hey. The following build command should be used in the docker file.

CGO_ENABLED=1 go build -tags gssapi -o app .
