### ISSUE TITLE
Empty values provided by runner while fetching docker secrets

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1223]
### Describe the bug
When we try to fetch docker secrets from runner using space CLI command `space-cli get all ./config --project myproject`. The field for docker secrets username, URL, pass are empty
### Expected behaviour
Show all the fields of docker secrets.
### Actual behaviour 
Doesn't show all the fields.
### Steps to reproduce

- Add docker secrets through mission control
- Use the command mentioned above to fetch all the space cloud-config
- Check the file named 02-secrets.yaml
- Docker secrets will be empty

### Your environment
- Space Cloud version: 0.19.0
- OS: Linux/ubuntu
- Kubernetes or Docker: docker
- The client api version (if applicable):
- Browser (if applicable): firefox

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Check for k8s as well

**Comment by YourTechBud** [comment]
Done
