### ISSUE TITLE
Mission control should persist the generated API token in API explorer

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1224]
### The problem faced currently?
In API explore, unchecking bypass security rule. Let's user specify his own HMAC / RSA token. Now mission control uses the new token while sending API request to space cloud.
But when I hit the refresh button. The generated token is gone. and bypass security rules is again checked.
This is really annoying.

### How can we solve it?
Mission control should persist the generated token in local storage, & use that token for the API request.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
This won't be done @sharadregoti as storing sensitive information like tokens in the local storage is never recommended.
