### ISSUE TITLE
Show a pop notification of disabling eventing config when removing database

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1225]
### The problem faced currently?
When a database is removed, mission control also sends a request for disabling eventing config.  But the user is not aware of eventing config getting disabled.

### How can we solve it?
Mission control should give a pop-up notification of disabling eventing config when you are removing database config

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@HeyItsJs I think this issue has already been resolved. Can you confirm?

**Comment by HeyItsJs** [comment]
Yupp. This is already done. While removing a database which is used in eventing, The message in popup notification is as follows:
`Eventing and realtime functionality will be disabled since this is the eventing db. Are you sure?`
