### ISSUE TITLE
Create a postman collection for space cloud

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1244]
### The problem faced currently?

Currently, if we want to test out some endpoints of Space Cloud directly or try out some API which isn't exposed through the API explorers in console, then the only way of knowing the endpoint details is checking the `server/routes.go` file. And even then we have to inspect the handler and find out all the possible fields in the body and put it manually in postman. 

### How can we solve it?

Let's make a postman collection for both the config and API endpoints for gateway and runner. And let's commit those postman collections into the space-cloud repository. This will make it easy for other contributors/users also to play around with space cloud API directly.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done
