### ISSUE TITLE
Unable to query multiple databases through the graphql api

### ISSUE THREAD

**Issue by marktanzy** [spaceuptech/space-cloud#1246]
### request path
 /v1/api/{project}/graphql

### graphql query
		query getUserDetail {
		  users: user (where: {account: {_eq: "test"}}, skip: 0, limit: 100) @mysql1 {
			id
			name
			account
			password
			account_mode
			user_roles (where: {user_id: "users.id"}) @mysql2(col: user_user_role) {
			  role_id
			  role_data (where: {id: "user_roles.role_id"}) @mysql3(col: user_role) {
				id
			    name
				description
			  }
			}
		  }
		}

### problem
it can not query multi databases(mysql1,mysql2,mysql3) successfully in one query, Is it because I use it incorrectly? I know that space-cloud supports multiple data queries from the space-cloud documentation.

I have read the space-cloud gateway repository code, the modules object hold graphql object, and graphql object hold crud interface, the crud module object just hold one crud interface, that means just hold one database conn,  I have not seen the gateway get different database conn crud object by the field directive which means dbAlias, so how the space-cloud gateway support multiple databases?

### wanted help
how should I do to use graphql query multiple databases

**Comment by YourTechBud** [comment]
Hey @marktanzy. Multiple database support is an enterprise feature. You will have to upgrade the SC cluster to PRO version in order to add multiple databases to a single sc cluster
