### ISSUE TITLE
support gcs setup on kubernetes with space cloud secrets

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1250]
### The problem

Currently, space-cli sets the `GOOGLE_APPLICATION_CREDENTIALS=/root/.gcp/credentials.json` environment variable on the gateway container during setup so that we can use space cloud secrets to configure gcs file store. 

However, this won't work in the case of a Kubernetes setup, as space-cli isn't used there.

### How can we solve it?

Two possible ways:
- The gateway container itself sets the environment variable on start
- We specify the environment variable in the Kubernetes setup YAML file.

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment]
We are using the environment variable in kubernetes setup yaml file
