### ISSUE TITLE
Space-cli get db-schemas get schemas in wrong order

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1255]
### Describe the bug
Suppose I have 3 tables A.B, C where A has a foreign key on B, and B has a foreign key on C.
If a use space-cli for getting database schemas ina file using get command. It fetches schemas in any order. Let's say after running the command i get schemas in order B,C,A. 
If i use space apply commad to apply the above schema file generated by get db schema i'll get error, because for creating table B, Table C should already be created.

### Expected behaviour
space apply db-schema-file should work seamlessly

### Actual behaviour 
space apply db-schema-file doesn't work

### Steps to reproduce
1) create tables as mentioned above with foreign keys
2) generate the schema file using space get db-schema command
3) apply the generated file

### Your environment
- Space Cloud version: - OS:
- Kubernetes or Docker:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Coming in `v0.20.0`
