### ISSUE TITLE
Add search bar in mission control for searching resources

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1259]
Space cloud has many resources like deployments, showing tables, graphql endpoints etc

If we have many resources of same kind it gets annoying to search for a particular resource. 
e.g -> if we have 25 tables in a database, mission control paginates the tables, And if you want to perform delete operation or untrack you have manually search for the table.

Having a search bar in each page for searching through these resource would be a great time saver.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.20.0`
