### ISSUE TITLE
space-cloud is not usable on docker

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#126]

**Comment by MichaelLeeHobbs** [comment]
RUN apk add --no-cache \
        libc6-compat

**Comment by MichaelLeeHobbs** [comment]
Here is a sample docker file

    FROM alpine:3.9
    WORKDIR /space-cloud
    RUN set -ex  \
      && apk add --no-cache ca-certificates unzip libc6-compat
    
    RUN wget https://spaceuptech.com/downloads/linux/space-cloud.zip -O space-cloud.zip
    RUN unzip space-cloud.zip \
        && rm space-cloud.zip \
        && chmod +x space-cloud
    
    COPY config.yaml .
    
    ENV PROD=false
    ENV PATH="/space-cloud:${PATH}"
    
    EXPOSE 8080
    CMD ./space-cloud run --config config.yaml

**Comment by YourTechBud** [comment]
The problem we are facing with the docker image is, what will be the default config file? If we don't want a default config file then mounting a config from the host will become mandatory! This isn't a cloud native way for doing things.

**Comment by MichaelLeeHobbs** [comment]
I've been working with Docker in production for well over a year now. Most apps that do anything remotely complex so this issue one of two ways. One, you create a custom docker image ie like above. Two, environmental variables. One app we work with you can pass in the config as an environmental variable as a json string. I didn't like the idea of having this massive json string in the docker stack file so we went with a custom build.

**Comment by MichaelLeeHobbs** [comment]
@YourTechBud If I were you I'd focus on the things that must be done in the core app and let config items be handled by docker and shell scripts as much as possible. I'm still working on the sample Todo App building it out as a docker stack. I'll try to publish something today.

Here's another thought for you. Why not create a collections config table? I've been working on a  solo project; RAD, for many months now that was effectively Space Cloud. One of the core items was API's could be added and removed in real-time. Like Space Cloud, it has a few default tables, Users, API, and Secrets. API's could be updated in real time via API calls and stored in the API table. Secrets were used for microserver endpoints to auth. The idea was that there is a core services container that coordinated everything to include multiple containers running core services and then microservice containers that would act as api endpoints. Unfortunately, I haven't had time to work on RAD in months. But now we have Space Cloud and I don't have to 😀

**Comment by YourTechBud** [comment]
So space cloud is capable of receiving the config via a HTTP request as well. I agree, a massive json string doesn't sound like a good idea! We are considering going the HTTP way and chucking files all together

**Comment by MichaelLeeHobbs** [comment]
Just thinking, how secure is config via HTTP?

**Comment by YourTechBud** [comment]
I love the idea of a `config` collection / table! We could also use something like consul or etcd for this. But using the database would make things a hell lot easier! All we'll need is the connection string and type of the database and that can be taken via an environment variable!

@MichaelLeeHobbs I'm glad Space Cloud could match upto your expectations. Would love to know more about RAD. Sounds pretty interesting and we could probably learn a lot from your experience. Why don't you join our discord server!? Here's a link: https://discord.gg/ypXEEBr 

@Jayesh333 lets adopt this as our default strategy?

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs not really it needs to be used only from a trusted network. However, we can always use JWT token to make sure only authenticated servers can update the config. HTTP gives us the ability to hot reload the config without having to restart the server

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs can we do this, have a default config file which exposes all the tables? Overriding this default can happen by mounting a config file or making a new image keeping the official one as the base. And once we have a admin ui up (#196) we can use that to configure it as well.

**Comment by MichaelLeeHobbs** [comment]
@YourTechBud I think you have the right idea. Should only need to pass in the db env variables via docker env or docker secrets

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs that support is on its way in #150

**Comment by YourTechBud** [comment]
Resolved in v0.10.0
