### ISSUE TITLE
Allow templating of webhook requests

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1267]
### The problem faced currently?
Currently the `webhook` security rule has a fixed payload and authorisation header. This can cause problems when we are trying to chain this request with another remoteservice.
### How can we solve it?
Accept a template field along with a claims field in the security rule object. I think the rest is pretty self explainatory.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done in Gateway

**Comment by HeyItsJs** [comment]
Done in mission control as well!
