### ISSUE TITLE
Add ability to encrypt, decrypt and hash fields conditionally

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1269]
Should be pretty straightforward. We have already done something similar for `force` and `remove` rules.

> Might require changes in security rule builder.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by KavishShah09** [comment]
I'm interested in working on this

**Comment by YourTechBud** [comment]
Done in Gateway

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.3`.
