### ISSUE TITLE
The fields section in remove, encrypt, decrypt and hash can be a variable

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1270]
## The problem faced currently?
Currently the `fields` field in the security rule object can only be an array of string. There is no mechanism to load this from the `args` object.
### How can we solve it?
We should make the `fields` an `interface{}` instead of `[]string`.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done in gateway

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.3`
