### ISSUE TITLE
Add health check mechanism for integrations which can be used to check if integration is up and running or not

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1271]
### The problem faced currently?
Mission control starts integrations but doesn't check if it really started. Because of this all the user may get an error when he clicks to `Open integration console` button.
### How can we solve it?
Add a `health` field in the config which can be used to check if the integration is up and running or not. Mission control can poll this periodically till a status code 200 is received signifying that the integration has started successfully. We can also include another status code (eg. 500) which signifies the integration could not be initialised and isn't functional anymore.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.3`
