### ISSUE TITLE
Add support for pod affinities

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1274]
Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done in `runner`

**Comment by HeyItsJs** [comment]
Done in mission control as well! Coming in `v0.19.3`
