### ISSUE TITLE
Add an optional timeout in the endpoint configuration of remote services 

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1277]
### The problem faced currently?

Right now, we can provide a `timeout` while calling an endpoint of a remote service. However, this means we need to change the client-side code that is consuming the remote service in order to change this timeout.  

### How can we solve it?

Let's add the `timeout` field (time in seconds) in the configuration of each endpoint in remote service. This field should be optional and space cloud should take a default value of `10` if Mission Control doesn't provide a value for `timeout`.

This `timeout` field can go in the advanced configuration panel of the remote endpoint configuration form.  

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by KavishShah09** [comment]
I can take this up for area/gateway

**Comment by sharadregoti** [comment]
Ok @KavishShah09

**Comment by HeyItsJs** [comment]
Done in Mission Control. All thanks to @KavishShah09!

**Comment by YourTechBud** [comment]
Done in gateway as well! Closing
