### ISSUE TITLE
Slow documentation loads

### ISSUE THREAD

**Issue by Xeoncross** [spaceuptech/space-cloud#128]
The [documentation](https://spaceuptech.com/docs/security/database) is questionably slow in loading and rendering taking several seconds to download everything, then another couple to render the actual page content.

**Comment by YourTechBud** [comment]
Such load times are totally unacceptable! @Jayesh333 we should get this fixed asap.

**Comment by Jayesh333** [comment]
There are couple of ways of doing that -
- improvising the current code of handlebars itself
- making it entirely static or using something like Hugo as suggested by @Xeoncross

**Comment by Jayesh333** [comment]
Before improving it we should first measure the current performance though. So that we can later measure the improvements.

**Comment by YourTechBud** [comment]
Shouldn't the CDN be helping us here? Lets not rule that out either.

**Comment by Jayesh333** [comment]
Yess it should be helping out here. Let's debug and figure out first what's causing the slow down

**Comment by narzeja** [comment]
You have this in your html head:

```
  <style>
    .async-hide {
      opacity: 0 !important
    }
  </style>
  <script>
    (function (a, s, y, n, c, h, i, d, e) {
      s.className += ' ' + y;
      h.start = 1 * new Date;
      h.end = i = function () {
        s.className = s.className.replace(RegExp(' ?' + y), '')
      };
      (a[n] = a[n] || []).hide = h;
      setTimeout(function () {
        i();
        h.end = null
      }, c);
      h.timeout = c;
    })(window, document.documentElement, 'async-hide', 'dataLayer', 4000, {
      'GTM-5KWD7NC': true
    });
  </script>
```
It seems to set the class of `html` to `async-hide` (`opacity: 0 !important;`) and removes it after 4000 ms.

**Comment by PascalLeMerrer** [comment]
I wondered at first if the documentation was built using space cloud, so I was concerned by its performances. It look like it's not the case, but this issue gives a poor image of the project.

**Comment by YourTechBud** [comment]
@PascalLeMerrer that's a fair point. Will try and get that fixed asap!

**Comment by YourTechBud** [comment]
Resolved
