### ISSUE TITLE
Mission control should add regex filtering of service logs

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#1283]

**Comment by HeyItsJs** [comment]
Do we mean simple `contains` search against what the user has typed or the user would type in some regex pattern?

**Comment by YourTechBud** [comment]
Regex.

Also, while we are at it lets add some controls to play the logs from a specific time period

**Comment by HeyItsJs** [comment]
Done. However we sticked with the `contains` query rather than regex.
