### ISSUE TITLE
Changing remote service type changes security rules

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1289]
### Describe the bug
After creating a remote service with type space cloud. I have applied the security rule to that endpoint type webhook. after saving the changes.
I tried changing the remote service type to internal. After clicking save the remote service type is changed. But it also changes the security rule for that endpoint from webhook to allow

### Your environment
- Space Cloud version: 
- OS:
- Kubernetes or Docker:
- The client API version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.3`
