### ISSUE TITLE
Atomic / Conditional Writes Supported?

### ISSUE THREAD

**Issue by Xeoncross** [spaceuptech/space-cloud#129]
There are a couple common types of database writes that are needed for many applications.

1. Atomic Counters (Increment / Decrement)
2. Race-safe updates
3. Transactional / Relational updates

### Details

1. Atomic counters are handy for synchronizing multiple clients writes without clobbering the data. MySQL, MongoDB, Redis, DynamoDB, etc.. all support them.

2. Race-safe updates (sometimes know as conditional-updates) insure that two mutations at the same time to a given object don't leave it in a mixed state. Most engines support this. For example, MySQL supports this with `UPDATE ... WHERE ...` while DynamoDB supports this with [Conditional Expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html)

3. Transactional Updates: #48

### Actual Issue

When a client attempts each of these types of actions, how are they handled? If a engine function issues these, how is the result returned over NATS to the calling client? Can documentation be added for these types of db/store mutations?

**Comment by Jayesh333** [comment]
We have  [batched mutations](https://spaceuptech.com/docs/database/transactions) and atomic counters now in all the supported databases @Xeoncross

Are our updates race-safe? @YourTechBud. I am not quite sure about it.

**Comment by YourTechBud** [comment]
@Xeoncross and @Jayesh333. Yes all updates are race-safe since they are executed as a transaction. If two clients end up performing an increment at the same time, one will fail. 

Instead of failing the transactions, we can have row level locks as well to carry them out one after the other. This would be pessimistic and cause a huge performance hit

**Comment by Jayesh333** [comment]
As per my views, since SC is designed to be a high throughput data access layer, it should always perform optimistic updates and let the client handle retries.

**Comment by YourTechBud** [comment]
Sounds good

@Xeoncross all mutations to the database do not go via nats to preserve ordering guarantees. SC directly opens up a transaction makes those conditional updates. If the transaction was successfully committed, SC sends a 200 status code else a 500 along with the error message.
If you were talking about a transaction across databases, that's not what we support.

**Comment by YourTechBud** [comment]
Solvednin `v0.11.0`
