### ISSUE TITLE
Support type uuid for Postgresql Database

### ISSUE THREAD

**Issue by KiSchulte** [spaceuptech/space-cloud#1295]
### At the moment track tables on Postgresql DB fail if the table has a uuid defined column?

Would be great if you can add the uuid type for the schema creation to make track possible out of the box.
For now, I've followed your advice and added the table via mission control without any filed definition, so it was added schemaless.

**Comment by YourTechBud** [comment]
@sharadregoti this should be a fairly straightforward process.

**Comment by YourTechBud** [comment]
Done
