### ISSUE TITLE
Limit clause not working if it's value is provided through graphql query variable

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1321]
### Describe the bug
Passing limit clause directly in the args of graphql query works. But if you provided the value of limit clause which is an integer through graphql variables.
Space cloud throws an error. Invalid type received for limit
### Your environment
- Space Cloud version:
- OS:
- Kubernetes or Docker:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Coming in `v0.19.4`
