### ISSUE TITLE
Validate audience & issuer claim of jwt token

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1322]
### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@HeyItsJs is this done in mission control?

**Comment by HeyItsJs** [comment]
Yes @YourTechBud

**Comment by HeyItsJs** [comment]
Coming in `v0.19.4`
