### ISSUE TITLE
No list of supported databases

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#133]
It's not very clear which databases we support. We should probably add a list of supported databases in readme and docs. It must also include all the postgres and MySQL adapter based databases that we support because of supporting MySQL and postgres like TiDb and CockroachDb @YourTechBud

**Comment by YourTechBud** [comment]
@Jayesh333 Lets get this in the Readme in the first half itself. Its already there here https://spaceuptech.com/docs/database

**Comment by elvarb** [comment]
https://spaceuptech.com/
https://spaceuptech.com/images/index/plugNplay.png

That image is showing various databases that are not supported or not yet supported.

**Comment by Jayesh333** [comment]
True @elvarb . We intend to support all databases from that image. Right now we only support 3 - MySQL, Postgres and MongoDb. We need to make it clear in readme which databases we support and which we are looking to support in the near future.

**Comment by elvarb** [comment]
Looking forward to Elasticsearch support, maybe there should be a ticket for each future supported database so people can watch those issues specifically.

**Comment by YourTechBud** [comment]
Hey @elvarb thats an amazing idea. Why don't you create the first issue requesting elasticsearch support and what features you expect in it?

**Comment by YourTechBud** [comment]
@Jayesh333 lets close this? I guess you've already implemented this one!

**Comment by Jayesh333** [comment]
Yes I have already implemented this.
