### ISSUE TITLE
Limit height of rows in table data viewer

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#1336]
It's ideal to hide excess y-content instead of word-break and displaying everything 

![Screenshot 2020-10-03 at 12 22 06 PM](https://user-images.githubusercontent.com/3975305/94985317-3bf19c80-0573-11eb-9b2d-725a76ca5452.png)

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by HeyItsJs** [comment]
Thanks for bringing this up @s-kris. Will get this done in `v0.19.4` itself which is about to be released by tomorrow.

**Comment by HeyItsJs** [comment]
Fixed. Coming in `v0.19.4`
