### ISSUE TITLE
Document how client libraries work

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#134]
Also link the various client libraries we already have

**Comment by YourTechBud** [comment]
Yes we should definitely do this. Will help us build and maintain new client libraries and make it easier for contributions. Maybe @AliabbasMerchant can help. He has written the the entire python driver himself!!!

**Comment by AliabbasMerchant** [comment]
Yup. Seems good. :+1:

**Comment by YourTechBud** [comment]
@AliabbasMerchant lets finish the python engine library then work on this? @Jayesh333 is this high priority right now?

**Comment by YourTechBud** [comment]
Not required since we promote GraphQL now
