### ISSUE TITLE
Provide option to change page size of table for each resource types in Mission Control

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1360]
When dealing with multiple resources, one might often want to see 20/50/100 items per page rather than 10. Hence we should provide an option to the user to change the page size.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
List of resources for this task:

- Database section
  - Tracked collections table
  - Untracked collections table
  - Prepared queries table
- Filestore section
  - Security rules table
- GraphQL API section
  - Remote services table
  - Endpoints table
- Eventing section
  - Event triggers table
  - Security rules table
  - Event schemas table
- Deployments section
  - Deployments table
- Secrets section
  - Secrets table
  - File secrets table
  - Environment variables table
- Ingress routing section
  - Ingress routes table

**Comment by Saif-Ali-Kamal** [comment]
As per ant design and my testing it automatically shows page size selector if data is more than 50
