### ISSUE TITLE
Let the services deployed in space cloud access kubernetes resources

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1367]
### The problem faced currently?
Currently, the services deployed through space cloud in Kubernetes cannot access Kubernetes resources like config maps, secrets etc...

### How can we solve it?
Like service routes, we can have service roles where we define rules that states which service can access which Kubernetes resources.

An example of a single resource object
`{
  "name": "yourPermissionName",
  "project": "",
  "service": "<serviceid>",
  "type": "cluster | project", // provide cluster level access or project level access
  "rules": [
    {
      "apiGroups": [""],
      "verbs": ["get","watch","list"],
      "resources": ["pods","configmaps"]
    }
  ]
}`
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done
