### ISSUE TITLE
Docs "edit docs!" footer and github url at navigation url different

### ISSUE THREAD

**Issue by nicknonis** [spaceuptech/space-cloud#137]
The url at footer of page "Edit docs!" sends user to different github page from the github link at top right of navigation bar.

Endpoint for footer url: https://github.com/YourTechBud/space-cloud/tree/master/docs/manual
Endpoint for navigation bar url: https://github.com/spaceuptech/space-cloud

**Comment by YourTechBud** [comment]
Got it. You think you can fix that?

**Comment by nicknonis** [comment]
Sure! Shall I keep it pointed at /docs/manual?

from:
https://github.com/YourTechBud/space-cloud/tree/master/docs/manual
proposed change:
https://github.com/spaceuptech/space-cloud/tree/master/docs/manual

**Comment by YourTechBud** [comment]
Yes. That looks good!
