### ISSUE TITLE
Post process rules don't work with linked data

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1381]
### Describe the bug
Post-process rules such as `remove`, `encrypt` (on the response fields) doesn't work in case of linked data in a DB read operation.

### Steps to reproduce

Add a mongo db database

Create the following schemas:
```
type users {
  _id: ID! @primary
  name: String
  
  posts: [posts] @link(table: posts from: _id to: user_id)
}
```

```
type posts {
  _id: ID! @primary 
  title: String
  user_id: ID
}
```

Then insert some users and their posts.

Then secure the `read` operation of the `posts` table with a `remove` rule that removes the `res.title`.

Then make the following query:

```
query {
  users @mongo {
    name
    posts  {
      _id
      title
    }
  }
}
```

You will get the value of the title field. However, because of the remove rule, we shouldn't be getting the title field.

### Your environment
- Space Cloud version: 0.19.6
- Database: Mongo

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Works now
