### ISSUE TITLE
Conditional Event triggers

### ISSUE THREAD

**Issue by narayandreamer** [spaceuptech/space-cloud#1392]
### The problem faced currently?
In an e-commerce app suppose i have event triggers to send email, sms and push notifications to a customer upon order status change.
Now for certain statuses i only want to send only push notifications so don't want to invoke sms and email triggers.

### How can we solve it?

Either we can query database to get a value based upon which to invoke a trigger or simpler development would be to save json in space-cloud itself and based upon that we take the decision to invoke the trigger

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done in gateway

**Comment by YourTechBud** [comment]
Done in mission control as well
