### ISSUE TITLE
Can we integrate the likes of AWS lambda, etc. for the functions module

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#140]
Currently the functions module works only with engines which are deployed as microservices. While this works well to ease development, it does restrict the scalability and ops aspect of things.

Can we leverage the research and products already prevalent in the severless world like AWS Lambda? Like have a hooks / routes to trigger such FaaS as well as a part of our functions module?

**Comment by Jayesh333** [comment]
Serverless functions can now be triggered via the `remote-services` or via the `eventing` module of Space Cloud.
