### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#141]
Just want to say awesome work! Would love to see built-in support for LDAP and other types of Federated auth. 

For now, I'm going to write a custom sign-in function to handle this.

**Comment by YourTechBud** [comment]
Haha. Thanks for the love! What part of it did you love the most?

That's actually a great idea. I am more interested in adding this support via an engine (function) instead. You think you can contribute back the code for the LDAP auth engine once you are done?

**Comment by MichaelLeeHobbs** [comment]
Adding notes for latter. https://godoc.org/github.com/jtblin/go-ldap-client

**Comment by kaivalya97** [comment]
Would also like to see LDAP over SSL (Secure LDAP) support.

**Comment by YourTechBud** [comment]
The enterprise edition includes support SAML. We expect users to have an IDP in front of their AD, etc. Closing this for now.
