### ISSUE TITLE
Passing the where clause as a value returns an empty result

### ISSUE THREAD

**Issue by kevinpolar** [spaceuptech/space-cloud#1473]
### Describe the bug
Using graphql endpoint, filtering via the nested object property by passing a where clause as a variable results into an empty result

More info:
Database: Mongodb v4.2.4

As per the information provided:

> the database returns the result. But space-cloud data loader is not to verify the result as the where clause is not in the expected format.

Also a workaround can be used for those experiencing the same issue:

> A quick workaround for this would be to add a limit or sort option in the query. This will bypass the data loader.

### Expected behaviour
Results should show

### Actual behaviour 
Empty Result

### Steps to reproduce
Create a collection with a JSON/Object column

Sample:
```
type customer{
  _id: ID! @primary,
  date_created: DateTime @createdAt,
  date_updated: DateTime @updatedAt,
  info: Info
}

type Info {
  smart_card_num: String,
  first_name: String,
  middle_name: String,
  last_name: String,
  birthdate: DateTime
}
```

Insert Data with smart_card_num set to "1234567"
Use graphql endpoint to filter via the smart_card_num property inside the info object, passing the where clause as a query variable.

Sample Query:
```
query{
  customer(
    where: $clause,
    sor: "asc"
  ) @mongo
  {
    _id
    info {
      smart_card_num
      first_name
      middle_name
      last_name
      birthdate
    }
  }
}
```
Variable:
```
{
  "clause": { "info.smart_card_num": "1234567" }
}
```

### Your environment
- Space Cloud version: 0.20.0
- OS: linux
- Architecture: amd64
- Kubernetes on Amazon
- Container Runtime: docker://19.3.6
- Database: Mongodb v4.2.4

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Coming in 0.21.0
