### ISSUE TITLE
make data loader configurable (on / off)

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#1474]
### The problem faced currently?
Some times the current data loader is not able to able to validate the where clause, because of this though the database has returned some result as the data loader is not able to verify the result, space cloud doesn't send the result to the client.
For e.g-> space cloud is not able to validate the where clause containing `like` operator.

### How can we solve it?
Space cloud should allow configuring the data loader at the database level. Meaning data loader for each database can be turned on / off independenltly

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done
