### ISSUE TITLE
Secure initialization for SQL databases

### ISSUE THREAD

**Issue by ollykel** [spaceuptech/space-cloud#149]
Just want to say that I think this is a great project, even though it's still in beta. Keep up the good work!

I noticed in the [docs for configuring databases](https://spaceuptech.com/docs/database/config) that you seem to recommend using the root user's login credentials for SQL databases. Best practice would be to advise users to create a new user for each service, then grant that user privileges only on the app's database. Granting root user access to an app is risky.

(As a side note, consider adding support for reading the connection string from a secure file to support services like [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/)).

To guide users towards secure practices I propose adding the following steps to space-cloud init when a SQL database is selected:
- Ask the user to _temporarily_ provide root user access to the database
- Create a new database (ask for a name on the command line, default to the project name)
- Create a new user and grant them all privileges on the new database
    - Ask for a user name, default to the database name + "_space-cloud"
    - Ask for a password, using a randomly generated password as a default. Require them to retype the password for confirmation.
- Format the user's credentials and the database name into the connection string

For ease of use you could also automatically initialize the users table, but that could be its own issue.

Hope this helps!

**Comment by YourTechBud** [comment]
Hey @ollykel!! That's actually a great suggestion! A quick clarification though. We do not recommend, using the root user at all. We should reflect that in the docs though. Also, currently you as the user have to create the database user roles and define the roles and tables.

> (As a side note, consider adding support for reading the connection string from a secure file to support services like Docker Secrets).

We should absolutely do that. Can you raise a separate ticket for that??

> For ease of use you could also automatically initialise the users table, but that could be its own issue.

We should definitely do that. But how can we accomodate the fields the user might want to capture? We do not restrict the user to the columns allowed in the `users` table. The are a few minimum columns which needs to be there, but apart from that you can add multiple columns.

**Comment by ollykel** [comment]
The user can always log into the database as an admin after it has been initialized and add new columns to the users table:
```SQL
ALTER TABLE users ADD COLUMN foobar VARCHAR(64);
```
This way the minimum columns will be there, but the user will not be restricted to them.

Creating a new database and user and granting privileges only takes a few queries, so that should be manageable. Other than initializing the users table, it probably is best to leave creating tables to the user for the near future, since creating an ORM that can manage tables and migrations like Django can be time-consuming.

**Comment by YourTechBud** [comment]
Awesome! I understand your point better now. I'm taking two things away from this. Prompt me if i missed anything.

- There should be a better way to manage secrets like db connections (we already have an issue on that open)
- Auto set-up the `users` table to make life a lot easier

Can you create another ticket for the second point?

**Comment by ollykel** [comment]
Great! That was essentially the point of this issue. Also remember to change the default conn strings for sql-mysql and sql-postgres to use a different username than root.

**Comment by YourTechBud** [comment]
Perfect! So @ollykel can you open up two tickets? One for correcting the docs and one for auto creating the `users` table?

We can't use this ticket since the title seems to suggest something else.

**Comment by YourTechBud** [comment]
The appropriate issues have been opened here: #150, #158, and #159. Hence closing this one!
