### ISSUE TITLE
Support for Varchar field

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1496]
### The problem faced currently?

The type `ID` in schema gets auto-generated even if the field is nullable. This is not desired for optional fields. Rather we can have a type `Varchar` with `@size` directive that never auto-generates values

### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
The ID field won't be autogenerated if it was marked as Nullable.
