### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by looterz** [spaceuptech/space-cloud#153]
What are the current plans regarding HTTP/2 support for the REST API? I think it would make sense to be HTTP/2 by default, and have an option for opting into the older protocol or support falling back.

**Comment by YourTechBud** [comment]
Thats actually a great suggestion! The golang http driver defaults to HTTP/2. Its on the client to initiate the http requests using http/2. The js client consumes the rest endpoints also defaults to http/2 (if supported by the browser). On the other hand, all other clients (in different languages use the gRPC endpoint which uses http/2 and protobuf under the hood.

So i believe we already have this feature implemented!

**Comment by looterz** [comment]
Okay awesome, thanks!
