### ISSUE TITLE
Replace "root" in default connection string for SQL databases

### ISSUE THREAD

**Issue by ollykel** [spaceuptech/space-cloud#158]
Currently the docs and space-cloud init default to using the root user in the MySQL connection string. It would be better to use a different name like "user" to guide users away from actually connecting with the root user. Something like this:
```yaml
conn: "user:my-secret-pwd@/project"
```

**Comment by YourTechBud** [comment]
We need to fix this in the `template.go` file in the `config` folder. Need to fix this in the docs as well.

**Comment by ledex** [comment]
As far as I can tell this has to be changed in the config/generate.go.

**Comment by YourTechBud** [comment]
@ledex you are right. My bad!
