### ISSUE TITLE
Auto-generate "users" table at initialization for SQL databases

### ISSUE THREAD

**Issue by ollykel** [spaceuptech/space-cloud#159]
It would be easy to do with one query, provided the user has CREATE permission on the database. This is how it's done in [the docs](https://spaceuptech.com/docs/user-management/overview):
```SQL
CREATE TABLE users (
  id    VARCHAR(50) PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  name  VARCHAR(50) NOT NULL,
  pass  VARCHAR(50) NOT NULL,
  role  VARCHAR(50)
);
```
The user will still be able to modify the table after initialization using ALTER TABLE statements, so they won't be limited to these fields, it'll just make it easier to get started.

Of course, you'll want to check if the user has already created a users table first. This query should work for that in MySQL:
```SQL
SELECT COUNT(TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = "users";
```

Hope this helps!

**Comment by ledex** [comment]
The table might need to change with when #84 is implemented.

**Comment by YourTechBud** [comment]
@Jayesh333 you think we should do this? We technically can using the schema module!

**Comment by YourTechBud** [comment]
We will soon be deprecating the user man module in favor of a auth integration. Ref #1112
