### ISSUE TITLE
Real Time TODO App does not work

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#171]
What? Tried to run https://github.com/spaceuptech/space-cloud/tree/master/examples/realtime-todo-app

docker run --name mongoTest -p 27017:27017 -d mongo:latest
space-cloud.exe run --config config.yaml

Opened index.html in Chrome twice.
Chrome1: Tried to create an account with many different variations. 
Email: a@a.com
Name: auser
Password: qwertyuiop
Response: 409 Conflict - {"error":"User with provided email already exists"}
Tried to login which obviously failed: 404 Not Found - {"error":"User not found"}

In command line console:
Starting server on port 8080
2019/04/20 11:48:30 Err:  mongo: no documents in result

In mongodb there is a collection todos but not a collection for users. I've even tried adding to the config:

        users:
          rules:
            read:
              rule: allow
            create:
              rule: allow
            update:
              rule: allow
            delete:
              rule: allow
          isRealtimeEnabled: false

Expected: User to be created and to be able to login.

**Comment by YourTechBud** [comment]
Try changing the port and change the url provided in the html file.

`space-cloud.exe run --config config.yaml --port 8090`

**Comment by MichaelLeeHobbs** [comment]
No difference.

**Comment by YourTechBud** [comment]
Oops! just realised the bug. @Jayesh333 just fixed it. Its probably getting build right now! Download the space-cloud version `v0.6.7`! It contains the fix

**Comment by YourTechBud** [comment]
@Jayesh333 we should get the functional tests in place now. We are closing in to `v1.0.0` now! Sorry @MichaelLeeHobbs for the trouble.

**Comment by Jayesh333** [comment]
Yess! We should get functional tests in place.

**Comment by MichaelLeeHobbs** [comment]
Where is the download at? The only ones I can find are on https://spaceuptech.com/ and are not updated.

**Comment by Jayesh333** [comment]
Its live now @MichaelLeeHobbs. The travis build took a couple of minutes.

**Comment by MichaelLeeHobbs** [comment]
Yeap, got it working. I've also updated/fixed https://github.com/spaceuptech/todo-app I want to do a few more things with the todo-app then I'll send a pull request your way.
