### ISSUE TITLE
space-cloud does not connect to mongo when ran from inside a container

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#173]
Expected: space-cloud to run and connect to Mongo container

Actual: space-cloud running in container alpine:3.9

Dockerfile.server.dev

    FROM alpine:3.9
    #WORKDIR /usr/src/app
    WORKDIR /space-cloud
    RUN set -ex  \
      && apk add --no-cache ca-certificates unzip libc6-compat
    
    RUN wget https://spaceuptech.com/downloads/linux/space-cloud.zip -O space-cloud.zip
    RUN unzip space-cloud.zip \
        && rm space-cloud.zip \
        && chmod +x space-cloud
    
    COPY config.yaml .
    
    ENV PROD=false
    #ENV PATH="/usr/src/app:${PATH}"
    ENV PATH="/space-cloud:${PATH}"
    
    EXPOSE 8080
    #CMD ./space-cloud run config.yaml
    CMD ["space-cloud", "run", "config.yaml"]
    #CMD ["sleep", "900"]

docker-compose.yml

    version: '3.7'
  
    services:
      mongo:
        image: mongo:latest
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        networks:
          - db
  
      server:
        build:
          context: ./server/
          dockerfile: ../docker/Dockerfile.server.dev
        image: todo-server-space-cloud
        restart: always
        depends_on:
          - mongo
        environment:
          - NODE_ENV=development
          - CHOKIDAR_USEPOLLING=true
        volumes: # For webpack dev server to use our local files
          - ./web:/usr/src/app
        networks:
          - api
          - db
  
      web:
        build:
          context: ./web/
          dockerfile: ../docker/Dockerfile.web.dev
        image: todo-web-space-cloud
        depends_on:
          - server
        environment:
          - NODE_ENV=development
          - CHOKIDAR_USEPOLLING=true
        volumes: # For webpack dev server to use our local files
          - ./web:/usr/src/app
        networks:
          - api
  
      haproxy:
        build:
          context: ./HAProxy/.
          dockerfile: ../docker/Dockerfile.HAProxy.dev
        image: todo-haproxy-space-cloud
        networks:
          - api
        ports:
          - "80:80"
        depends_on:
          - server
          - web
  
    networks:
      db:
      api:
  
    volumes:
      db-data:

All containers come up fine however, I do not see a connection from the server to mongo. API request in Web simply timeout. I have connected to the server container and have verified it can ping mongo and connect to it on port 27017. I've even stopped and restarted the server container thinking it might be a timing issue. 

I'm wondering if this might be a case of another missing library as with "libc6-compat".

Space Cloud seriously needs way more logging or an option to turn on verbose logging. 

Once I figure out this last issue I'm going to repost the Todo-App as a full stack docker-compose example project. I figure it will be nice to have a docker-compose up example project for Space Cloud.

Thanks,
Michael

**Comment by YourTechBud** [comment]
You are not passing the `--config` in your docker command. Also, the current docker release isn't functional. It doesn't expect to load any config file at all. The config file needs to be loded via an HTTP request. We already have an open ticket here #126. Let's move the conversation there?

We also have a ticket related to logging #57. Its on high priority!

**Comment by MichaelLeeHobbs** [comment]
Uhh opps :D Thanks! Working great now!
