### ISSUE TITLE
Need Versioned Downloads

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#174]
Long term only having the latest download is not acceptable. Need to be able to version lock ie ```wget https://spaceuptech.com/downloads/linux/space-cloud-0.6.7.zip```

edit: Better yet yarn add space-cloud@0.6.7

**Comment by YourTechBud** [comment]
Hey @MichaelLeeHobbs. I totally agree with your point. `v0.7.0` is slated to be the first release of space cloud. We'll be versioning the releases on GitHub and our site!

**Comment by YourTechBud** [comment]
@Jayesh333 lets get this done in Travis itself. Its time to start versioned releases.
