### ISSUE TITLE
Server URL Path for Proxies

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#176]
I've noticed the path for the server starts with /v1/api. Assuming there could be a v2, v3, etc it would be better to have it as /api/v1, /api/v2, etc in regards to proxies. Think HA Proxy for example. If you have the version first then every time there is a new route version you'd have to HA Proxy config or have a regex matcher. While regex would work it has its own issues.

    acl container_api           path_beg        -i /v1
    acl container_api           path_beg        -i /v2
    acl container_api           path_beg        -i /v3

vs

    acl container_api           path_beg        -i /api

With the second method, you could even send different versions to different containers.

**Comment by YourTechBud** [comment]
That's a great suggestion. @Jayesh333 let's do this?

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs, shouldn't we also let the project id come before v1? Something like
`/api/:project/v1` ?

**Comment by YourTechBud** [comment]
Not sure if we'll be doing this
