### ISSUE TITLE
db.liveQuery(...).where(condition).subscribe(onSnapshot, onError) - onSnapshot not called for deletes

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-cloud#177]
Expected: onSnapshot to be called when db.delete(...) is called

Actual: Document(s) are deleted but onSnapshot is not called

delete

    removeTodo(id) {
        db.delete('todos').where(and(cond('id', '==', id))).one().then(res => {
            if (res.status !== 200) {
                console.log('Delete Failed:', res)
            }

        }).catch(ex => {
            // Exception occured while processing request
            console.log('Delete Exception:', ex)
        });
    }

subscription

    componentDidMount() {
        // Get user id from local storage
        const userId = localStorage.getItem('userId')

        const onSnapshot = (docs, type) => {
            console.log('onSnapshot > docs', docs)
            this.setState({todos: docs}, () => {
                console.log('onSnapshot > setState > this.state.todos', this.state.todos)
            })
        }
        const onError = (err) => {
            console.log('Live query error', err)
        }
        const condition = cond('userId', '==', userId);
        db.liveQuery("todos")
            .where(condition)
            .subscribe(onSnapshot, onError)
        db.liveQuery("todos")
            .where() // testing not sure if this even works
            .subscribe((doc) => {
                console.log('subscribe > doc', doc)
            }, onError)
    }

**Comment by YourTechBud** [comment]
That's a bug for sure. @MichaelLeeHobbs you think you can raise the same issue on the js repo as well? Here's a link: https://github.com/spaceuptech/space-api-js

**Comment by YourTechBud** [comment]
The where clause must get an empty object. It should look something like this:
```js
db.liveQuery("todos")
        .where({})
        .subscribe((doc) => {
            console.log('subscribe > doc', doc)
        }, onError)
```

@Jayesh333 is this the expected behaviour?

**Comment by MichaelLeeHobbs** [comment]
@YourTechBud The change to the where made no difference. I'll raise the issue on js repo and see if I can fix it if that is where the issue is.

**Comment by YourTechBud** [comment]
@Jayesh333 is already on it!

**Comment by MichaelLeeHobbs** [comment]
I do not have any experience with go but it appears to me that the issue is in ```http.go``` I've dug fairly deeply into the space-api-js and could not find an issue there. I've watched the ws message and I'm not seeing any messages on deletes, only inserts. I have not tested any other operations yet.

I've read over the code in ```http.go``` but the go code is different enough from anything I've used in the past that I'm not entirely sure what is going on. However, to me seems like the issue is here:


	func (s *server) handleDelete() http.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) {
			...

			// Send realtime message in dev mode
			if !s.isProd && req.Operation == utils.One {
				...

				if idTemp, p := req.Find[idVar]; p {
					if id, ok := idTemp.(string); ok {
						if err != nil {  // <-- seems like it would only send a websocket message if there WAS an error
							s.realtime.Send(&model.FeedData{
								Group:     meta.col,
								Type:      utils.RealtimeDelete,
								TimeStamp: time.Now().Unix(),
								DocID:     id,
								DBType:    meta.dbType,
							})
						}
					}
				}
			}

			// Give positive acknowledgement
			w.WriteHeader(http.StatusOK)
			json.NewEncoder(w).Encode(map[string]interface{}{})
		}
	}}
	}

**Comment by YourTechBud** [comment]
That's a good catch @MichaelLeeHobbs. I've fixed it in `v0.7.1`. Does is solve the bug now?

**Comment by MichaelLeeHobbs** [comment]
Yes, I'm seeing websocket messages for deleted. There appears to be a bug in space-api-js. I'm taking a look at that now as JS is what I do on a daily basis.

**Comment by YourTechBud** [comment]
Awesome @MichaelLeeHobbs. Keep me updated. I would really love it if you could join our discord server. Would love to have you on board

**Comment by MichaelLeeHobbs** [comment]
@YourTechBud I'm going to join in a bit. Was planning to latter. 😄

**Comment by YourTechBud** [comment]
Awesome

**Comment by MichaelLeeHobbs** [comment]
Resolved
