### ISSUE TITLE
Add check for valid email

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cloud#183]
When signing up a user the validity of the email address should be checked by sending an email with a confirmation-URL. Also one should be able to set if a user with an unconfirmed email is allowed to sign in.

**Comment by YourTechBud** [comment]
How do you intend to do it?

**Comment by ledex** [comment]
I would return a 400 - Bad request stating that the given request does not contain a valid email-address.

**Comment by YourTechBud** [comment]
But how will we know if its a valid email address!?

**Comment by ledex** [comment]
Okay, valid might not be clear here. I mean syntactically correct so just checking against a regex.

**Comment by MichaelLeeHobbs** [comment]
Please check https://emailregex.com/ I tried to copy and paste but it does not paste correctly

**Comment by YourTechBud** [comment]
Im not sure how does this help us. It wouldn't stop anyone from entering an invalid email id. Maybe we should add support to verify email address by sending a verification email?

**Comment by MichaelLeeHobbs** [comment]
It only makes sure the email is in a valid format. We should actually send users an email with a link to validate they own the email address. Should also have the options to force users to validate before they can actually login.

**Comment by ledex** [comment]
That would be perfect. I updated the issue. The only question left is how to implement this:
Should space-cloud itself send the confirmation mail or should a foreign function be called which has to be implemented individually and then sends the mail? And where should the activation-endpoint be? You might want to have a short page stating that the activation has been successful.

**Comment by YourTechBud** [comment]
@ledex we have a module called `functions`. Maybe we can make an engine for handling this?

**Comment by ledex** [comment]
Is the module already implemented though? I cannot see it in the modules folder. If the functions-module is implemented it can be used to forward the verification request to a foreign function/service.

**Comment by YourTechBud** [comment]
@ledex its already implemented and has a dependency on Nats. In the code base, it is referenced as `faas`. Maybe we should refactor it as functions everywhere.

**Comment by ledex** [comment]
Okay. I will have a look into it this afternoon

**Comment by YourTechBud** [comment]
@ledex So lets create a ticket to refactor `faas` to `functions`?

**Comment by ledex** [comment]
Okay. See #198

**Comment by YourTechBud** [comment]
Awesome. Leaving this issue open though!

**Comment by YourTechBud** [comment]
This would get resolved as a part of #1112
