### ISSUE TITLE
Implement web/REST based admin ui

### ISSUE THREAD

**Issue by 8byr0** [spaceuptech/space-cloud#196]
### The problem faced currently?
- Managing users can only be done from DB client(not really sexy) or frontend client(needs work before being able to do so).
- Dealing with security rules can be tricky when they grow and become huge

### How can we solve it?
Implement web admin interface with the following features
- [ ] manage users (CRUD)
- [ ] manage collections / db (import / export)
- [ ] rules generator (and why not live update config with generated data)

**Comment by YourTechBud** [comment]
Do you see this as a web based tool or a desktop app? The final output of the admin ui will be the config file right?

**Comment by 8byr0** [comment]
You want to provide a cross database tool, right ? Let's provide a cross platform interface !

Actually a desktop app would only be a web based tool packaged in atom/electron/whatever ! (when it's about manipulating datas, it's absolutely overkill to do a native app as it will cost more in development & maintain time. And web apps are powerfull enough when packaged: see VScode, slack, postman...)

So I think we should just develop a web admin and then package it to executable if needed !

**Comment by YourTechBud** [comment]
@8byr0 absolutely! We'll use electron or something similar. Im just thinking about the user flow. Will the app be making changes directly to the local config file or will it connect to a space-cloud dev instance which in turn will manipulate the config file?

We should get @Jayesh333 and @ledex in this one as well.

**Comment by 8byr0** [comment]
No I don't think so!
You connect to space-cloud instance that has exposed endpoints and from server-side callbacks, space cloud processes requests and deals himself with the file.

Because if you edit config file from client, it implies that you're running it on the same machine as the server. And as the aim is to be able to run SC in prod, you want to control it remotely !

**Comment by YourTechBud** [comment]
I agree

**Comment by YourTechBud** [comment]
However @8byr0 we will have to get some authentication mechanism to let a user change the configurations. Something like a `super-admin` or a `super-dev` role

**Comment by 8byr0** [comment]
Yes, something you can set in config file for example ? 
Like this:
```yaml
modules:
    web-admin:
        su: mySuAdmin
```
And at first launch set password (best for security as you would not have to hardcode password in config file)

**Comment by Jayesh333** [comment]
Great idea @8byr0. The idea of decoupling the admin UI from the config file for remote control sounds super cool!! 

Few questions I have here:
- Does the authentication mechanism suggested here expects the space cloud to always start with a config file? Should we consider starting `space-cloud` without a config file and then configuring it completely via the admin UI? The `space-cloud` can be just started with the authentication details as flags (just an idea).
- How would the admin UI update the config of multiple `space-cloud` of same project running on different servers?

**Comment by YourTechBud** [comment]
@Jayesh333 Lets just consider updating a single `space-cloud` instance for now! But I love the idea to start `space-cloud` with just a few flags / environment variables and let the admin ui take care of the rest.

**Comment by MichaelLeeHobbs** [comment]
I was actually thinking that all space-cloud should need to start is environmental variables for the db. The rest could be pulled from the DB or if the DB is empty then it would initialize the db.

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs that's an important feature. That would be needed when you want to setup an entire cluster of space cloud or something similar. There are two possible ways the operations would work:
- query the database on every request to fetch the security rules (high latency but guaranteed to be the latest config)
- query the db once and load the config in memory.

Which one to go forward with? I'm more inclined towards the former. But I have this feeling, config from database should be an enterprise feature. Its more ops related rather than than development related.
