### ISSUE TITLE
Make a end to end quick start using docker

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#199]
### The problem faced currently?
The current steps require the user to follow several steps in order to get a sample app running.
### How can we solve it?
Maybe we can make a getting started guide using docker compose. We can do something like this: https://github.com/MichaelLeeHobbs/space-dock

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Resolved in `v0.11.0` by introducing a quick start based on the explorer in mission-control
