### ISSUE TITLE
Add overview of avavible variables in docs

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cloud#201]
### The problem faced currently?
It is not clear which variables (args.auth, etc.) are available in the for rules in the config.yaml
### How can we solve it?
Make an overview of all variables that are at one's disposal when creating rules in the config.yaml.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We can simply make it another section in the same page!

**Comment by YourTechBud** [comment]
Solved
