### ISSUE TITLE
Realtime should work when id is not string

### ISSUE THREAD

**Issue by SarveshKargutkar** [spaceuptech/space-cloud#205]
### The problem faced currently?
when we try to implement the realtime feature with integer as an id ,it faces issues
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This can be an easy fix honestly. Need some time to get it right though.

@SarveshKargutkar which data type did you want to use for _id anyway?

**Comment by AliabbasMerchant** [comment]
@YourTechBud Lets close this then. PR #268 has solved this issue

**Comment by YourTechBud** [comment]
Yup
