### ISSUE TITLE
Add support MongoDB Object ID's

### ISSUE THREAD

**Issue by didair** [spaceuptech/space-cloud#206]
### The problem faced currently?
Right now when using a standard mongo collection and auto generated id's you cannot query that item later for e.g. updating since there's a mis-match with the data type.

### How can we solve it?
Option 1: The client sdk's could have a method to generate an Object ID (new or with an string)
Option 2: The back-end automatically generates an Object ID on the `_id` parameter.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This is an important one to be addressed. It holds true exclusively for MongoDB since it has a custom ObjectID type it assigns.

**Comment by didair** [comment]
Seems like the MongoDB library exports a function to generate an Object ID from a string. Maybe look into that. [https://www.tutorialspoint.com/mongodb/mongodb_objectid.htm](https://www.tutorialspoint.com/mongodb/mongodb_objectid.htm)

**Comment by YourTechBud** [comment]
@didair I'm not quite sure how will we implement this. Space could can only speak json. So there is no ObjectID type it understands. Maybe we can incorporate this in the schema validation feature #78

**Comment by YourTechBud** [comment]
@didair would it be okay if SC automatically generates an _id field which is string?

**Comment by didair** [comment]
@YourTechBud since that is the workaround used by probably most people yes that would be an OK solution!

**Comment by YourTechBud** [comment]
@sharadregoti you think we can add this in the schema validation module?

**Comment by sharadregoti** [comment]
yes we can

**Comment by YourTechBud** [comment]
This will be solved once we resolve #453

**Comment by YourTechBud** [comment]
Added in `v0.13.0`
