### ISSUE TITLE
Rework the role-model for the auth-module

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cloud#208]
### The problem faced currently?
The client can set the role when creating an user. This is a security issue, especially when the role is used for authorization rules in the config file.
### How can we solve it?
Rework the role-model so that no unauthorized and no unauthenticated entity can change the role of a user.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@ledex can you also describe a possible suggestion?

**Comment by YourTechBud** [comment]
@ledex we can break this down into 3 aspects if I'm not wrong.
- Default role: We should definitely do this. Its a great idea. Basically you are suggesting that a nee user cannot set the role property during creation. I agree with this.
- Rules for modifying the role: Can this be taken care by the security rules instead? That would let the developer write more complex rules as well. Eg. update role only if payment is made.
- Provision for 3rd party authenticators: A tricky piece to get right. Maybe it deserves to be in a separate ticket. Will help the rest track progress as well.

**Comment by ledex** [comment]
@YourTechBud yes, I agree that it might be better that the rules for modifying rules should be taken care of by the securety-rules. Would be nice if this could be combined.
Regarding the 3rd-party-authenticators: I also would suggest putting this in another feature.

**Comment by YourTechBud** [comment]
Cool. Let's get this done then

**Comment by VedantParanjape** [comment]
i think we can follow the role system that is present in discord @YourTechBud @ledex

**Comment by YourTechBud** [comment]
@VedantParanjape thats actually a good idea. But i feel we should not impose any authentication system like role based authentication, etc. Not every app will have an admin who will be changing roles, etc. Lets just have a default role and have security rules dictate who can update it.

**Comment by YourTechBud** [comment]
We wont be continuing the user management module. It will come as a service using the `functions` module

**Comment by akhedrane** [comment]
Could you externalize Auth N/Z module to use custom solution like [casbin](https://github.com/casbin/casbin).

**Comment by YourTechBud** [comment]
@akhedrane casbin looks super exciting. We can definitely do that. Cause you raise a separate issue for that?

**Comment by akhedrane** [comment]
ok.

**Comment by akhedrane** [comment]
#438
