### ISSUE TITLE
Rename "engines" of in the functions module to "service"

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#210]
### The problem faced currently?
Currently a collection of functions running is called an `engine`. This name is highly misleading and vague.
### How can we solve it?
Let's rename (or rebrand) `engines` as `services`
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by VedantParanjape** [comment]
can we simply replace all engines with services? @YourTechBud

**Comment by YourTechBud** [comment]
Yup. Engine becomes service and engines becomes services

**Comment by YourTechBud** [comment]
Fix coming in `v0.9.0`
