### ISSUE TITLE
Can we transform functions module of space cloud into a full fledged service mesh?

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#212]
Currently the functions module does not provide monitoring and security for the functions which might restrict a lot of Enterprise usecases. Simply providing these two can transform the functions module into a full fledged service mesh. 

We already have a strong security rules mechanism in space cloud. We can leverage that for the service mesh. Combining the simplicity of the functions module and the enterprise readiness of a service mesh like Istio could greatly help the end user.

Any thoughts or features we should consider?

**Comment by YourTechBud** [comment]
Will require #211 to be done before work can start on this one.

**Comment by YourTechBud** [comment]
Coming in v0.9.0
