### ISSUE TITLE
"Listen" address configuration option

### ISSUE THREAD

**Issue by didair** [spaceuptech/space-cloud#222]
Add a configuration option for space cloud to make it listen on a certain IP or domain.

Example:
```
id: some-id
secret: some-secret
listen: some.domain.com / som.eip.add.ress
```

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Thanks for bringing up this feature request @didair 

Adding this can make a web server like nginx almost redundant for most of the small applications.

What's your thoughts on this? @YourTechBud

**Comment by YourTechBud** [comment]
This does sound like an interesting request. But it will work only for the http based protocols. It does seem to make sense to me.

**Comment by YourTechBud** [comment]
@didair why exactly did you need this feature?

**Comment by YourTechBud** [comment]
This is now possible all thanks to the routing module
