### ISSUE TITLE
Add app hosting feature

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#235]
### The problem faced currently?
The number of routes to host a react or angular app are too high. It makes the config file size unnecessarily large.
### How can we solve it?
Have a native option to host an app (react and angular) as well.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 isn't this default now? `v0.9.0` resolves this right?

**Comment by Jayesh333** [comment]
Yess this is resolved in `v0.10`
