### ISSUE TITLE
Security Issue in EditProfile

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#242]
### Describe the bug
Currently, (although not implemented as yet), the EditProfile method takes in the foll params:
* _id: (str) The user's id
* email: (str) The (optional) new email id
* name: (str) Then (optional) new name
* password: (str) The (optional) new password

Consider the following:  
I call the profiles() function, which gives me all the users and their ids.  
Now, I can easily call the EditProfile function, and using the ids, update the data of all the users.  

### Solution
We need to include the password field also in the EditProfile function and match the password against the id and allow it to update only if it matches.

### Your environment
- Space Cloud version: v0.9.0
- OS: All
- The client api version (if applicable): -
- Browser (if applicable): -

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by AliabbasMerchant** [comment]
We can resolve this by changing the function EditProfile to:
`def edit_profile(self, _id: str, password: str, email: Optional[str] = None, name: Optional[str] = None, new_password: Optional[str] = None):`

**Comment by AliabbasMerchant** [comment]
Also, what about the token? It will also be updated, right?

**Comment by YourTechBud** [comment]
Lets refer to _id as id since the former is mongo specific.
You should be able to apply the read and update rules to the profiles and editProfile functions respectively. I don't think we need to include the password.

**Comment by YourTechBud** [comment]
@AliabbasMerchant if I've addressed your concern, let's close this issue?

**Comment by AliabbasMerchant** [comment]
@YourTechBud So is the current implementation of EditProfile correct?

**Comment by YourTechBud** [comment]
Yes. The one in the PR seems to be correct

**Comment by AliabbasMerchant** [comment]
Cool
