### ISSUE TITLE
Need to explicitly specify rules for the users table

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#243]
### Describe the bug
I can easily create a user keeping the config as shown in https://www.spaceuptech.com/docs/user-management/overview  
However, to perform any read or write operation, we need to explicitly specify the rules.

Also, `users` is a very common name. The programmer may already have such a table.  
Lets rename the table to something uncommon, like `SpaceCloud_Users_Table`.  
So that there is no conflict in the table names

### Expected behaviour
Either include in the docs that you have to explicitly specify, or give permissions internally itself.

### Actual behaviour 
Explicit Rules are currently required.

### Steps to reproduce
Call the Profile or Profiles routes.

### Your environment
- Space Cloud version: v0.9.0
- OS: -
- The client api version (if applicable): -
- Browser (if applicable): -

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@AliabbasMerchant we should specify in the docs that rules are required to read the users collection. User management isn't going to be a production ready module. It's just for easy prototyping

**Comment by YourTechBud** [comment]
@AliabbasMerchant if I have addressed your concern then let's close this issue
