### ISSUE TITLE
Update Docs for User table

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#244]
The docs currently state that for the users table (SQL), we need to have the password column as:
`pass  VARCHAR(50) NOT NULL,`

However, we are using bcrypt to hash the password. This gives password of length 60.

We need to update the docs to reflect this:
`pass  VARCHAR(60) NOT NULL,`

PS: Ideally, we should use `BINARY(60)` instead of `VARCHAR(60)`, but this requires explicit conversion to a binary-type object in go.

**Comment by YourTechBud** [comment]
The docs have already been updated but aren't live. Closing the issue
