### ISSUE TITLE
Move http handler functions to utils/handlers package

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#251]
### The problem faced currently?
Currently the http handler functions are located in their respective modules package. Some are even in http.go in the root. This makes it extremely scattered and difficult to navigate
### How can we solve it?
Lets move these handlers to the `utils/handlers` package
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@Inconnu08 you want to take this issue up?

**Comment by Inconnu08** [comment]
@YourTechBud Yes, glad to take it!

**Comment by YourTechBud** [comment]
Solved in v0.9.0
