### ISSUE TITLE
move server to its own package in utils/server

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#261]
The `grpc_server.go` is getting super large. Let's move `server.go`, `grpc_server.go` and any other related file to another package (`utils/server`)

**Comment by Inconnu08** [comment]
@YourTechBud I'm up for this 🖐

**Comment by YourTechBud** [comment]
@Inconnu08 great. Its a big one though.

**Comment by Inconnu08** [comment]
Hopefully, I'll pull it off

**Comment by YourTechBud** [comment]
Awesome!

**Comment by YourTechBud** [comment]
Solved in v0.9.0
