### ISSUE TITLE
FileMan Bugs

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#284]
### Describe the bug
1. Does not work for Windows. The file separator does not match. Everywhere, we have mentioned "/", which is Unix Styled. We need to instead put `os.PathSeparator`
2. There is a small but dangerous bug. If we specify the filenames as `"/../"`, it allows us to insert into the parent folder, which is dangerous. We must use absolute paths to check.

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Thats a good one. @AliabbasMerchant are you gonna be taking this issue up?

**Comment by Inconnu08** [comment]
I'm up for this if @AliabbasMerchant is busy.

**Comment by YourTechBud** [comment]
Sure @Inconnu08. Take this up!

**Comment by Inconnu08** [comment]
on it!
