### ISSUE TITLE
Include the profiler endpoints in the space-cloud binary 

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#293]
### The problem faced currently?
No way to profile cpu and ram usage for doing optimisation
### How can we solve it?
Include the profiler endpoints in the main binary. Have a `--profile` flag to explicitly enable it.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Inconnu08** [comment]
I'm working on this

**Comment by YourTechBud** [comment]
Coming in `v0.10.0`
