### ISSUE TITLE
Fix the bugs in the docs

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#297]
Here's a list of issues i found with the docs
- [x] the manual quick start page seems to have an outdated config file displayed
- [x] lets add a point in the user man page that the password is bcrypted
- [ ] java docs must have the imports as well to maintain consistency with the other docs
- [x] the golang docs are using an api.Init(). They should use the api.New command instead
- [x] let's have all the `Note:` in bold
- [ ] many code examples are using an if - else pattern to check response. Lets avoid that.
- [ ] for the golang and java docs it seems like data can be inserted using hashmaps only. This isn't the case
- [ ] we should have each page in the doc to start with what they will cover. Something like this: https://spaceuptech.com/docs/database/read
- [x] the format of the code across languages isn't consistent on the database read page
- [x] no golang batched operation code snippet
- [x] the file man rules needs to be an array not a map. Opening an issue for this as well. Lets not forget to update the security rules for file man as well then
- [x] file man docs not updated with code snippets. Non js libraries have a download function as well. @Jayesh333 lets accomodate that
- [x] we are not talking about reading connection string from env anywhere?

**Comment by Jayesh333** [comment]
Resolved
