### ISSUE TITLE
The result sent by call of functions module is inconsistent with the crud module

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#301]
### Describe the bug
The functions module returns the result directly instead of sending it in a map with the `result` field, as in CRUD module.
### Expected behaviour
The functions module must return the result in the same fashion as crud module.

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by AliabbasMerchant** [comment]
I think we should not send it as a map for the gRPC part. gRPC already has the response thing.  
We can send it as a map for the http part, if you wish. We should change only the http code. Not the functions code.

**Comment by YourTechBud** [comment]
For http lets keep it in `result`

**Comment by Jayesh333** [comment]
Not for grpc? @YourTechBud

**Comment by YourTechBud** [comment]
@Jayesh333 they work differently! They have a method like `getValue`

**Comment by Jayesh333** [comment]
Okay! All I want is the client libraries to return the same result irrespective of what Space Cloud is returning, so that for end user, the experience is same no matter which language he choses
