### ISSUE TITLE
Have a task queue for SC

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#345]
### The problem faced currently?
Its difficult to queue and schedule tasks. Everything has to be done manually via functions.
### How can we solve it?
It would be amazing if we could have or integrate with a task manager for queuing and scheduling tasks we with automatic retries and some strong guarantees.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
What type of tasks are we talking about? @YourTechBud

**Comment by YourTechBud** [comment]
So let's say an SC function was invoked by some client. The function on a temporary basis can send an ack to the client and schedule the heavy computational task for later. This taks would then trigger another function when certain criteria is met, which can do the heavy processing.

**Comment by AliabbasMerchant** [comment]
@YourTechBud So after we finish the heavy processing, we again send an ack to the client?

**Comment by YourTechBud** [comment]
@AliabbasMerchant we don't really need to send an ack to the client in this case. However, the application can choose to push a notification or email or even do nothing for that matter.

**Comment by YourTechBud** [comment]
Fixed in `v0.12.0`
