### ISSUE TITLE
SC allows requests even if incorrect project name is provided

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#347]
### Describe the bug
Suppose the client requests to connect to "projectA" on port X.
If SC is running on port X and doesnt have the project "projectA" (but has project "projectB"), in some cases, the client is given an error, but in other cases, it connects to "projectB"

### Expected behaviour
An error should be returned to the client

### Steps to reproduce
Use "allow" as the rule for file man or for services&functions

### Your environment
- Space Cloud version: v10.0.1
- OS: Windows
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Resolved in 0.10.1
