### ISSUE TITLE
Realtime Security Bug

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-cloud#362]
### Describe the bug
When the realtime module is not enabled, but the table is realtime enabled, the "initial" results are sent to the client, but a nats error is logged on space cloud
### Expected behaviour
An auth error must be sent to the client
### Actual behaviour 
No error is sent to the client
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Fixed in `v0.12.0`
