### ISSUE TITLE
"getting started" buttons for all programming languages (js,py,go) link to nonexistent pages

### ISSUE THREAD

**Issue by nicobrinkkemper** [spaceuptech/space-cloud#368]
### Describe the bug
The getting started buttons link to non-existing pages

### Expected behaviour
Clicking to button leads to a page describing how to set-up space-cloud with desired programming language

### Actual behaviour 
Page not found

### Steps to reproduce
- Run space-cloud mission control
- open in browser 
- click any of the programming language buttons under getting started

### Your environment
- Space Cloud version: 0.11.0
- OS: Linux

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 seems like a quick fix. Can you take this up?

**Comment by Jayesh333** [comment]
Yess, let's add redirects for the old links as a quick fix and fix the links in the next version.

**Comment by YourTechBud** [comment]
Sounds good. Assigning it to you

Thanks @nicobrinkkemper for pointing it out.

**Comment by YourTechBud** [comment]
@Jayesh333 is this fixed?

**Comment by YourTechBud** [comment]
Fixed
