### ISSUE TITLE
Make mission-control mobile responsive

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#369]
### The problem faced currently?
One cannot try the quick start from the mobile itself, since the mission control is not mobile responsive

### How can we solve it?
Make each screen of Mission control (login, welcome, create-project, project overview and all modules page, etc) mobile first
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 lets close this if its done?

**Comment by Jayesh333** [comment]
It's not done yet
