### ISSUE TITLE
Add CI/CD to space-cloud and all of its client libraries

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#370]
Right now, all of these tasks are manual:
- Testing SC and their client libraries
- Building and uploading archives of `space-cloud` binaries
- Building docker image of `space-cloud` and pushing it to docker hub
- Building Mission Control and uploading its archive

We should add CI/CD so that all of these tasks can be triggered and executed automatically whenever code is merged into `master`.

**Comment by YourTechBud** [comment]
Space Cloud now has a working CI pipeline based on github actions
