### ISSUE TITLE
Fix the quick start in README

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#374]
### Describe the bug
The current README has an outdated quick start about the realtime todo app.  

### Expected behaviour
The latest quick start in the docs is based on explorer in mission control. The README should reflect this latest way of quick start 

### Actual behaviour 
The readme shows the incorrect oudated realtime todo app example for quick start

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Fixed
