### ISSUE TITLE
Document how to run SC in clustered mode

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#375]
### The problem faced currently?
The current docs does not shows how to run SC in clustered mode or a distributed environment, even though SC supports it.

### How can we solve it?
Add a section for clustered mode in various deployment guides(docker, manual) 
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This is particularly important now since running SC in clustered mode requires `consul`

**Comment by Jayesh333** [comment]
Done in `v0.13.0`
