### ISSUE TITLE
Add a debugger to explorer

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#376]
### The problem faced currently?
It's hard to understand why a particular request to SC has failed. Is it because of the security rules and if so what am I missing?
 
### How can we solve it?
The Mission Control has a cool explorer to try out SC APIs. Since this explorer has access to all the project config (including the secret and the security rules) and the request being made, it can help user debug what went wrong by providing useful info to the user.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This can be solved by introducing #462 and #1120
