### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#378]
### The problem faced currently?
Right now there is no first class support for integrating OAuth (google, facebook, twitter, github signin/signup)  

### How can we solve it?
By adding first class APIs to SC directly to integrate OAuth providers
 
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Lets add supports like this in a microservice. Now that we can deploy stuff as well, it will be easy to auto setup things.

**Comment by YourTechBud** [comment]
Duplicate of #1112

**Comment by theDemon92** [comment]
May be supertokens can be build right into space-cloud since it's also opensource
