### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#379]
### The problem faced currently?
Right now, users have to write a backend function to put data in a cache like Redis

### How can we solve it?
By adding first class support for Redis. The client should be able to mention whether a data is cacheable while inserting it via `options` 

For example: 
`db.insert(collection).doc(doc).options({cache: true}).apply()`

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Done
