### ISSUE TITLE
space-cloud tries to connect to db even if it is disabled

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#396]
even though i disable sql db in config
SC still tries to connect

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Hey @sharadregoti , does this bug still exist? Try it out once and perhaps even solve it.

**Comment by Jayesh333** [comment]
I think this is related to #485

**Comment by YourTechBud** [comment]
solved in `v0.17.0`
