### ISSUE TITLE
default security rules are not working

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#410]
### Describe the bug
Default security rules seem to be ignored

### Expected behaviour
If no rule for a table is found, then default security rule should be appied

### Actual behaviour 
My default security rule is to  allow all operations. Still i get the error that no table or collection was found

### Steps to reproduce
Don't create a table/ collection. Leave the default security rules as it is. Try inserting some document in database

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 I could not reproduce this issue. Closing it for now. Reopen if this issue still exists.
