### ISSUE TITLE
Support for Google cloud storage is missing in the diagram

### ISSUE THREAD

**Issue by rmkanda** [spaceuptech/space-cloud#422]
Issue: Support for Google cloud storage is missing in the diagram

Space Cloud supports Google cloud storage but in the below logo only AWS is mentioned this is misleading. 

<p align="center"><a href="https://www.spaceuptech.com"><img src="https://spaceuptech.com/icons/space-cloud-block-diagram1.png" alt="Space Cloud"></a></p>

<img src="https://spaceuptech.com/icons/space-cloud-detailed.png"  style="max-width: 80%" alt="Detailed Space Cloud architecture" />

Please add Google cloud storage also in the diagram.
Unable to find source of the diagram to fix and raise pull request

**Comment by YourTechBud** [comment]
Thanks for pointing it out @rmkanda!

@Jayesh333 let's get this updated!

**Comment by Jayesh333** [comment]
Yess! Also I think we need to swap the positions of databases and custom functions, since databases are the core of Space Cloud.

**Comment by YourTechBud** [comment]
@Jayesh333 do we have an eta on this?

**Comment by Jayesh333** [comment]
Yes. I have a couple of other ideas as well to improve the readme like showing a graphic of graphql query in the readme itself for which I have created a separate issue as well. We can batch all those graphics changes together.

So let's do it in `v0.15`?

**Comment by YourTechBud** [comment]
Sounds good

**Comment by YourTechBud** [comment]
Fixed
