### ISSUE TITLE
Automatically save database connection string on clicking setup database.

### ISSUE THREAD

**Issue by takeerdevs** [spaceuptech/space-cloud#428]
### Describe the bug
When creating new database connection string and click setup database throws an error **Could not setup db**  

### Actual behaviour 
When adding new database connection string and click setup database has to save connection string first automatically and then proceed.. currently, you have to manually click save button, which i forgot and ran into finding solution.  

### Steps to reproduce
Navigate to database section, overview tab, add new connection string and click on setup database
### Your environment
- Space Cloud version: v0.12.0

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 maybe we can first hit the save config endpoint and then setup the database? You think this is possible?

**Comment by Jayesh333** [comment]
Hey @takeerdevs, the mission control in Space Cloud `v0.13.0` does not have setup database button. The mission control sets up the database internally whenever you provide a correct connection string. 

The new mission control has significant UX improvements. Check it out and let us know your feedback!
