### ISSUE TITLE
Add default url and default rule when a db is manually enabled

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#432]
### The problem faced currently?
The default url and rule isnt automatically added when a database is manually enabled
### How can we solve it?
Would be great if we could inject them in the config dynamically. Maybe we can inject the default url and rule in each db while creating a new project. Doesn't matter as long as the db is disabled
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Resolved in `v0.13.0`
