### ISSUE TITLE
Link schema module with graphql

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#433]
### The problem faced currently?
While making dynamic joins is really cool, it would be great if we can infer these joins from the schema module so we do not need to specify it in the graphql query.
### How can we solve it?
Not really sure. But lets link the schema and graphql module some how
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Done in `v0.14.0`
