### ISSUE TITLE
JSON Schema for validating configuration files

### ISSUE THREAD

**Issue by dhruvin2910** [spaceuptech/space-cloud#439]
### The problem faced currently?
AFAIK, space-cloud is configured via providing json, yaml, or (for a limited subset) generating via cli. That works great.

It'd be great if it can have a [schema](https://json-schema.org) file using which docs and autocompletion with types can be provided from inside the supporting IDEs or editors.

### How can we solve it?

There are a couple of ways to solve it:

1. Write the schema manually
    * We must update it every time the [Config](https://github.com/spaceuptech/space-cloud/blob/master/config/config.go#L6) changes.
    * Which is fine for projects with guaranteed configuration spec stability. RFC.
    * Easiest to do
2. Generate the schema
    1. From the code
        * A script must be run before committing or merging into master. But hooks will do.
        * Go has a great parser provided built in, we can leverage that.
        * Not easy. Initial investment in time, but greater payoffs.
    2. From the documentation
        * A script must be run same as above.
        * Output of go doc can be used to scrape specific parts for generating schema.
        * Not easy, great if we don't want to parse code, can be written in almost any language.

Recently I've been working on improving developer experience with open source projects. Let me know if this addition will help developers using it, and I'll create a PR.

**Comment by YourTechBud** [comment]
Hey @dhruvin2910, are you talking about the config file?

I think documenting the config file will be amazing. Thats a great idea. But lets start this after `v0.13.0` release?

Also, i think documenting the rest / graphql apis is far more important than the config file since mission control (the admin ui) generates a config file for sc. You think you can help in that regard?

**Comment by dhruvin2910** [comment]
> Hey @dhruvin2910, are you talking about the config file?

Yes, but for IDEs and Editors, but mainly for intellisense, as developers won't read the schema.

> I think documenting the config file will be amazing. Thats a great idea. But lets start this after v0.13.0 release?

I am not sure about the workflow for providing same configuration file across multiple instances of space-cloud. Correct me if I'm wrong about multiple instances.

1. Will I need to generate the config using dashboard beforehand, save it locally, then provide the same, and not edit it using UI in production?
2. Or the instances (or pods) need to share common volume? Since the admin ui seems to be making persistent config changes (to the disk).
3. Or something I'm missing.

> Also, i think documenting the rest / graphql apis is far more important than the config file since mission control (the admin ui) generates a config file for sc. You think you can help in that regard?

I'm thinking along the lines of providing open api spec for the REST API (if not done already), as graphql schemas can directly be used by the IDEs or editors.

**Comment by dhruvin2910** [comment]
Here's a schema for [prometheus.yml](https://github.com/SchemaStore/schemastore/commit/f7432272a99f4031d670e65ecf14afab115c3b5f) in action.

![Screenshot 2019-10-15 at 11 44 06 AM](https://user-images.githubusercontent.com/9679326/66804818-1c67fb00-ef41-11e9-99dd-04f9bfb22269.png)

**Comment by dhruvin2910** [comment]
Initial schema without constraints is [here](https://github.com/dhruvin2910/space-cloud/blob/c1a73e16ee3bd4fe83b9ced967f5a2d53babd776/protocol/config.schema.json).

**Comment by YourTechBud** [comment]
This looks really good!
