### ISSUE TITLE
Postgres database Cannot create table with column name "user"

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#441]
### Describe the bug
error | pq: syntax error at or near "user"
getting the above error while creating a table with column name "user"
### Actual behaviour 
in Postgres, user is a reserved keyword 
so column name cannot be user
but the error message doesn't help figuring out the error
### Steps to reproduce
type dummy3 {
  id: ID! @id
  user : String!
}
use the above schema to create a table
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Closing since the is nothing we can do about it
