### ISSUE TITLE
Postgres database creating table with hyphen separated column names does not create table

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#442]
### Describe the bug
Creating a table with a column name "end-user" does not create a table in the database
but the schema is added to mission control UI in Schema & Overview section of Database

In Postgres column name should not be in form "end-user" it should be in "end_user"
but mission control returns success creating table with status code 200
### Steps to reproduce
type dummy3 {
  id: ID! @id
  end-user : String!
}
execute the above schema
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@sharadregoti I think this will be fixed once we implement the new APIs for config changes.
