### ISSUE TITLE
Change event payload as per Cloud Events CNCF spec

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#449]
Instead of reinventing or imposing our own format for event payload, let's use some standard format which is widely acceptable. 

The [JSON event spec](https://github.com/cloudevents/spec/blob/v1.0-rc1/json-format.md) by [Cloud Events Specification](https://github.com/cloudevents/spec) are great for this as per my opinion.

This is my suggestion as per Cloud Events Specification:
```json
{
    "specversion" : "1.0-rc1",
    "type" : "$EVENT_TYPE",
    "source" : "<space-cloud-node-id>",
    "id" : "<unique-uuid>",
    "time" : "<ISO 8601 format date string>",
    "data" : {}
}
```
I suggest the following values for `$EVENT_TYPE`:
- `CRUD_CREATE`
- `CRUD_UPDATE`
- `CRUD_DELETE`
- `<CUSTOM>`

**Comment by YourTechBud** [comment]
What about headers. Think we should set some header as well so the destination can validate wheather SC has made the request or not?

**Comment by Jayesh333** [comment]
```
What about headers. Think we should set some header as well so the destination can validate wheather SC has made the request or not?
```
Headers are not specific to events. They can even be required in case of any other webhook requests such as remote service. So let's discuss them here #450

**Comment by YourTechBud** [comment]
Added in `v0.13.0`
