### ISSUE TITLE
Webhooks specifications

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#450]
Instead of reinventing or imposing our own specifications for webhooks, let's use some standard which is widely accepted

The [HTTP webhooks specification](https://github.com/cloudevents/spec/blob/v1.0-rc1/http-webhook.md) by [Cloud Events Specification](https://github.com/cloudevents/spec) are great for this as per my opinion.

This is my suggestion as per Cloud Events Specification:

- Every request should contain `Content-Type` and `Authorization` headers 
- Consider webhook invocation being successful on any 2xx status code in response.
- Don't send webhook notifications to the webhook target if it responds with `410 Gone` status code
- If a webhook target sends `429 Too many` status code then we should retry after the number of seconds mentioned by the webhook target in `Retry-After` header.

The last two points can be ignored in case of making webhook request for security rule - `rule: webhook` and for services. They only makes sense in case of eventing as per me.

**Comment by YourTechBud** [comment]
In case of the `Service` module, we'll have a client token as well.so 2 tokens will have to be sent to the target. Maybe we should always set SCs token in the `Authorization` header and set the client's token is a custom header?

**Comment by Jayesh333** [comment]
@YourTechBud Not very sure as to which one should be in Authorization and which one should be in custom header. I have seen a lot of examples where people use custom header like `X-<product-name -Signature` so that webhook targets can confirm that the webhook was performed by that particular product/organization.

**Comment by Jayesh333** [comment]
But none of them had to forward a request from client to webhook

**Comment by Jayesh333** [comment]
For the headers, I can think of two more strategies:
- Forward all headers from client.
- Allow user to configure whether he wants to forrward all headers to client on each webhooks url.

In any of the above case, we can/should take additional headers which user wants to set on a webhook. These headers will override any headers from the client.

**Comment by YourTechBud** [comment]
```
Every request should contain Content-Type and Authorization headers
```
I think SC's token should be set in the `Authorization` header since it will always be there. The client's token can be in another header.

Let's not forward all headers in this release or allow the user to set custom headers. We'll do it if someone asks for it.

**Comment by Jayesh333** [comment]
Cool, we can keep the client's token in a custom header like `X-SC-Client-Token`.

**Comment by Jayesh333** [comment]
For sake of simplicity, I feel that we can do this with the status codes:
- For security rule webhook, `200` means authorized and anything other than that to be unauthorized 
- For event triggers, `200` means processed and anything other than that to be failed resulting in retry as per the retry logic.

Not very sure about the services part though, @YourTechBud you can help there maybe?

**Comment by YourTechBud** [comment]
We have decided that SC will forward the client's token in the `Authorization` header. It will also include it's own header in the `x-sc-token` header.

This is coming in `v0.15.0`
