### ISSUE TITLE
Schema suggestions

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#453]
After going through the entire schema thing, I had few thoughts for better semantics and flexibility. I have listed them below:

- The `ID` type should automatically generate a random, unique UUID string if not provided by the mutation.
-  A table/collection should have the flexibility to use multiple fields with type `ID`. Type `ID` should not be looked as `primary key`, since primary key is a constraint and not a type. 
- The `@id` directive should be replaced by `@primary` for better semantics. This directive should be used to put Primary key constraint on a particular field.

**Comment by YourTechBud** [comment]
Fixed in `v0.13.0`
