### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by shubham4443** [spaceuptech/space-cloud#458]
Discord fab coming in between pagination when there are too many tables in database

![Screenshot from 2019-10-23 13-17-34](https://user-images.githubusercontent.com/51191406/67370005-9c244400-f597-11e9-8356-cefd06cd9787.png)

**Comment by Jayesh333** [comment]
You have any idea of what we can do? @shubham4443

**Comment by shubham4443** [comment]
Give bottom margin

**Comment by YourTechBud** [comment]
@shubham4443 can you help fix that?

**Comment by Jayesh333** [comment]
This can get fixed if we change the location of discord button to either in sidenav or topbar as suggested in #570

**Comment by s-kris** [comment]
@Jayesh333 #570 is to provide a link in about section. Moving the FAB is on 7th point here https://github.com/spaceuptech/space-cloud/issues/577#issuecomment-569337346

**Comment by Jayesh333** [comment]
Done. Now the discord fab has been removed. And instead, we have a join discord card in the project overview screen.
