### ISSUE TITLE
Tracing in Space-Cloud

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cloud#462]
### The problem faced currently?
One graphql-query to Space-Cloud can result in many queries made to the modules attached to space-cloud. This can make finding issues quite hard especially when one query of the client results in queries to the database and to a function:
> Why took the request 5 sec? Was it the database or the function that is being called?

### How can we solve it?
Implement tracing that allows the admin to see how long each "sub-request" takes. This way you could spot errors or problems more easily. This could look something like [this](https://www.elastic.co/guide/en/apm/get-started/current/images/apm-distributed-tracing.png). 
It also would be nice as an admin to get informed about the "sub-requests" that take longer than average. 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍 

cc: @YourTechBud

**Comment by YourTechBud** [comment]
We will be fixing this as a part of #57

**Comment by YourTechBud** [comment]
Coming in `v0.19.2`
