### ISSUE TITLE
Cannot mutate an existing table when its schema is changed

### ISSUE THREAD

**Issue by shubham4443** [spaceuptech/space-cloud#467]
I get this error in the terminal where space-cloud is running when I mutate an existing table whose schema I changed recently.

2019/10/25 13:21:59 Eventing Error: event could not be updated Error 1054: Unknown column 'remark' in 'field list'

there is no such column as 'remark' in my table. I had to drop my table and re-create it to fix this issue.

**Comment by YourTechBud** [comment]
Hey @shubham4443 this isn't a schema module problem. It's a problem with the schema used for the `events_log` table.

@Jayesh333 we need to make sure we both are using the same schema

**Comment by YourTechBud** [comment]
Fixed in `v0.13.0`
