### ISSUE TITLE
[RFC] Schema SDL for primary key

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#476]
## The `@primary` directive

The `@primary` directive is used currently to make a particular field as primary key. However it has the following limitations:
- No support for composite primary key
- Only a field of type `ID` can be made primary.

I suggest the following SDL for the `@primary` directive:
- Should be applicable for following field types:
  - ID
  - Integer
- Arguments:
  - strategy: ENUM (optional):
    - AUTO (default): Will generate random unique string values for type `ID` and auto-increment/serial values for type `Integer`. If the user provides the value for this field in mutation, then the value from user will be used.
    - NONE: Will not generate any value. User will have to provide value during mutation.
- If the `@primary` directive is used on multiple fields in a type, then those fields should form a composite primary key

_Examples_ 

Composite primary key:
```graphql
type transactions {
  transaction_id: ID! @primary
  batch_id: ID! @primary
  date: DateTime!
  payload: String
}
```

In the above example, `transaction_id` and `batch_id` will together form a composite primary key.

Integer primary key:
```graphql
type orders {
  order_no: Integer! @primary
  amount: Float!
  date: DateTime!
}
```

Disabling auto-generation of primary key:
```graphql
type orders {
  order_id: ID! @primary(strategy: "NONE")
  amount: Float!
  date: DateTime!
}
```

**Comment by JoeyJanson** [comment]
@sharadregoti @YourTechBud Will this be assigned on a new milestone?

**Comment by HeyItsJs** [comment]
Hey @JoeyJanson, which part of this are you interested in? The _composite_ key part or supporting other types for primary key such as auto-increment integer?

**Comment by JoeyJanson** [comment]
> Hey @JoeyJanson, which part of this are you interested in? The _composite_ key part or supporting other types for primary key such as auto-increment integer?

Other types for primary key. It was the first issue I ran in to after connecting with an existing MySQL database.

**Comment by HeyItsJs** [comment]
It can be done for sure and definitely on our roadmap. Not sure whether it can be done in this release itself. @YourTechBud and @sharadregoti  would be able to tell that better.

**Comment by YourTechBud** [comment]
@JoeyJanson which datatype are you looking for? 
@HeyItsJs it will be very difficult to add support for auto incrementing keys. Our `linked` inserts feature will break in that case.

**Comment by JoeyJanson** [comment]
@YourTechBud The database gql schema is initialized with Integer as primary. I can't foreign the types (join) because the primary isn't of the type ID. So, it would be nice to have the @primary key support Integer as well.

**Comment by YourTechBud** [comment]
I see. I think we can make this work as long as the user provides the integer value upfront. Does that work?

**Comment by JoeyJanson** [comment]
> I see. I think we can make this work as long as the user provides the integer value upfront. Does that work @JoeyJanson?

Sorry for the delayed response; yes would work for me!

**Comment by YourTechBud** [comment]
Coming in `v0.20.0`
