### ISSUE TITLE
[RFC] Schema SDL for default values

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#478]
Right now there is no way to provide the default value for a particular field which is a common use requirement in most applications. For example, setting the `published` status of a blog post to `false` when inserting a blog post.

I suggest implementing a `@default` directive to solve this.

_Example_:

```graphql
type posts {
  id: ID! @primary
  title: String! @primary
  published: Boolean! @default(value: false)
}
```

**Comment by YourTechBud** [comment]
Done

**Comment by Jayesh333** [comment]
Is it done for all databases including mongo?

**Comment by YourTechBud** [comment]
Yes!
