### ISSUE TITLE
[RFC] Schema SDL improvements

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#479]
Right now the schema module in Space Cloud has the following limitations:

- Only type `ID` can have `@unique` and `@primary` constraints
- No way to override the field types being used in the underlying database. For example, there is no way of using the `TINYINT` type in MySQL for storing `Integer` values or there is no way of setting the character limit of a `String` field to 500.
- No composite primary and unique keys
- No default value constraints
- Indexes have to be created manually by the user
- Does not infers relations to make joins simpler

Some of these issues are addressed in the following issues with specs for solutions:
- SDL for Indexes #475 
- SDL for primary key #476 
- SDL for unique key #477 
- SDL for default values #478 
- Auto implying joins from relations #494 

Feel free to add your thoughts/suggestions here or on the specific issues!

**Comment by YourTechBud** [comment]
Closing this since only #476 is left
