### ISSUE TITLE
404 not found for  the web page of "function" 

### ISSUE THREAD

**Issue by tomzhang** [spaceuptech/space-cloud#487]
### Describe the bug
can not found the resources for "function" operation in help page
### Steps to reproduce
![function page not found](https://user-images.githubusercontent.com/541236/68290878-af6cfe80-00c3-11ea-80bd-bc262e606116.png)

### Your environment
- Space Cloud version: 
- OS: Mac
- The client api version (if applicable):
- Browser (if applicable): chrome

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Hey @tomzhang. We recently dropped the support for `functions` module in favour of [remote services](https://docs.spaceuptech.com/essentials/remote-services)

Join our [discord channel](https://discordapp.com/invite/ypXEEBr) if you want any help in migrating your existing `functions` to remote services. I will love to personally guide you through it.

**Comment by Jayesh333** [comment]
Fixed. Thanks, @tomzhang for bringing this up!
