### ISSUE TITLE
DBAlias instead DBType in db directives

### ISSUE THREAD

**Issue by akhedrane** [spaceuptech/space-cloud#488]
### The problem faced currently?

As the api goes public, for security reasons the clients should not know the db type (@mysql...).

### How can we solve it?
Make an alias to database like (@dbname).

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This sounds like a great idea. We should absolutely get this done

**Comment by YourTechBud** [comment]
Coming in `0.15.0`
