### ISSUE TITLE
Custom fields in signUp of user management module

### ISSUE THREAD

**Issue by VirajRG** [spaceuptech/space-cloud#49]

**Comment by YourTechBud** [comment]
@VirajRG Right now there are no provisions to add your own fields while using the user management api (`db.signUp()`). You can add fields by issuing an update query on the users table / collection though.

Also, in SQL (where we have a fixed table schema), you can add as many columns as you like. However, the user management module will only use the `id`, `name`, `email`, `pass` and `role` columns.

Currently the user management module returns the entire record / document when a user signs in. You should store private information is the users table / collection.

@Jayesh333 maybe we should restructure the user management module and make it production ready?

**Comment by Jayesh333** [comment]
Should we reflect on having an user management module in the first place? The only additional benefit it is providing now, over the user implementing the user management functionalities himself via the crud (which is more flexible) is avoiding the sign-in logic.

**Comment by YourTechBud** [comment]
That does makes sense. Ideally Space Cloud must have modules which integrates with other technologies. Shouldn't be anything more.

@Jayesh333 maybe we should see how authentication is done in other systems?

**Comment by YourTechBud** [comment]
We won't be doing this
