### ISSUE TITLE
Auto imply nested queries from relations in schema SDL

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#494]
Right now, user has to manually join related types in GraphQL queries like these:
```graphql
query {
  author @postgres{
    id
    name
    posts(where: {id: ""author.id"}) @postgres{
      title
    }
  }
}
```

It can be great if we can imply these joins from the schema. For example:

```graphql
type author {
  id: ID! @primary
  name: String!
  posts: [post] @relation
}

type post {
  id: ID! @primary
  title: String!
  user_id: author! @foreign
}
```

The `@relation` in above schema won't create any column but is mentioned so that such queries are possible:

```graphql
query {
  author @postgres{
    id
    name
    posts {
      title
    }
  }
}
```

While, the `@foreign` will create a column as well as a foreign key on the the column. The parent table key will be `id/_id` by default. But can be changed by the `to` argument like this:

```graphql
type post {
  id: ID! @primary
  title: String!
  user_id: author! @foreign(to: "name")
}
```

Similarly `@relation` directive will have it's default `to` argument as `id/_id` which can be overwritten.  For cross database joins, user can also mention db argument like these:

```graphql
type author {
  id: ID! @primary
  name: String!
  posts: [post] @relation(db: "mongo", to: "name")
}
```

> Note: This will be a breaking change. However, it will provide more clarity and transparency to user as to whether he is creating a foreign key or just creating a relation which can be used in his queries.

**Comment by Jayesh333** [comment]
As discussed with the team, here's the final tentative SDL that we wanna support for describing foreign keys and relations:

```graphql
type author {
  id: ID! @primary
  name: String!
  articles: [article] @link(from: id, to: author_id)
}

type article {
  id: ID! @primary
  title: String!
  author_id: ID! @foreign(table: author, to: id)
  tags: [tag] @link(table: article_tag, from: id, to: article_id, field: article)
  author: author @link(from: author_id, to: id)
}
type article_tag {
  id: ID! @primary
  article_id: ID! @foreign(table: article, to: id)
  tag_id: ID! @foreign(table: tag, to: id)
  article: article @link(table: article, from: article_id, to: id)
  tag: tag @link(table: tag, from: tag_id, to: id)
}

type tag {
  id: ID! @primary
  value: String!
  articles: [article] @link(table: article_tag, from: id, to: tag_id, field: tag)
}
```

The above schema should allow the user to make the following queries:

```graphql
query {
  author @db {
    id
    name
    articles {
      id
      title
      tags {
        value
      }
    }
  }
}
```

```graphql
query {
  tag @db {
    id
    value
    articles {
      id
      title
      author {
        name
      }
    }
  }
}
```
```graphql
mutation {
  insert_author (docs: [{
    name: "Author1",
    articles: [{
      title: "Article 1",
      tags: [{value: "Tag1"}, {value: "Tag2"}]
    }]
  }]
  @db {
  }
}
```

**Comment by YourTechBud** [comment]
As discussed, nested inserts for many-to-many relations will not be supported.
