### ISSUE TITLE
Date comparison in security rules

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#499]
### The problem faced currently?
Date based business logic have to be implemented via custom code. For example, preventing any form submissions after a particular date.

### How can we solve it?
Space Cloud has a very robust security module that validates incoming data. If we can introduce functions to generate current time in security rules then we can solve whole lot of date validation logic in security rule itself.

For example:

```json
{
  "rule": "match",
  "eval": "<=",
  "type": "DateTime",
  "f1": "now()",
  "f2": "2019-11-25"
}
```

This involves adding support for `DateTime` in `type` and a function `now` to generate current date
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We should add these helper functions as well:
- `utils.now()` - returns the current time
- `utils.addDuration('DATE_TIME_STRING', 2, 'seconds | minutes | hours | days')`

We should support two date time formats
- RFC3339
- `YYYY-MM-DD`

The data type should be `date`
