### ISSUE TITLE
The download config file steps in the quick start guide leads to errors

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#50]
I've heard quite a few people having troubles with downloading the config file step. Apparently copying and pasting the config directly in a file doesn't work.

@KhushalPShah faced the same issue I guess.

**Comment by Jayesh333** [comment]
Can we have some more context to this? Like on what OS does this problem arises and what errors are reported? @KhushalPShah

**Comment by YourTechBud** [comment]
I think this links back to #28.

**Comment by KhushalPShah** [comment]
> Can we have some more context to this? Like on what OS does this problem arises and what errors are reported? @KhushalPShah

I tried copying the contents of the config file, as well as downloading the config file.
Neither of it worked.
I tried it on Ubuntu.

**Comment by YourTechBud** [comment]
Whats the `space-cloud` version you are using?

**Comment by high-functioning-sociopath** [comment]
Unable to download config file.
Unsuccessful attempt to copy  and run the config contents(raw) to config.yaml
How does the space-up api pick up the index.html file? Because I tried saving the file at the same location as of config, but resulted in 404 not found error.

**Comment by Jayesh333** [comment]
When exactly did you get the 404 error? Immediately on running the space cloud or on making some request to space cloud via client api (if yes then which request)? Also what do you mean by space-up API pick up the index.html file?  And what's the version of the space cloud you are running? @high-functioning-sociopath

**Comment by high-functioning-sociopath** [comment]
Following the tutorial, I copied the config file and downloaded the index.html file from the todo example.
I started the space-cloud through terminal which said the server is running on port 8080.
So when I went to localhost:8080, it displayed the 404 HTTP error , which means it is not able to find the file.
So how does the space-cloud know which file (front-end, viz. todo app) to run? Because nowhere in the config file have I mentioned which file I want to run.

**Comment by YourTechBud** [comment]
@high-functioning-sociopath `space-cloud` doesn't host static files yet. Its a good idea to add that feature though. `space-cloud` only exposes the REST endpoints for the crud operations. Also, space cloud would throw an error if it couldn't load the config. @Jayesh333 we should add a log message saying "config loaded or something similar to make it more explicit.

You'll have to open the html file directly in the browser by double clicking it. I should have been more specific in the docs. The issue #28 does talk about this and what space-cloud really is.

Try opening the html file directly and then try?

**Comment by Jayesh333** [comment]
Yess agreed we should add a message saying config file loaded. Maybe we can also add a message saying that your *backend server* is up and running on port 8080 to make it more precise. Would that help? @YourTechBud @high-functioning-sociopath

**Comment by high-functioning-sociopath** [comment]
Oh okay. I'll try doing that. @YourTechBud 
Yes it would really be helpful for debugging. @Jayesh333 
Also if would be really great if the guide was clearly defined.

**Comment by YourTechBud** [comment]
@KhushalPShah I think your problem was different? Can you tell us what was it you faced? Like with the steps?

**Comment by Jayesh333** [comment]
@KhushalPShah is this problem still there?

**Comment by YourTechBud** [comment]
Resolved
