### ISSUE TITLE
Use a time bound context for each handler

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#502]
Currently some modules set a time bound context internally. The other modules (the ones related to config) do not use a context at all. 

We must create a time bound context in the handler function itself and pass it down to each module to make sure each handler function exits.

**Comment by YourTechBud** [comment]
Also we need to make sure that the `r.Body` in each http request is closed, even if the body wasn't used

**Comment by Jayesh333** [comment]
This is solved right? @YourTechBud

**Comment by YourTechBud** [comment]
No. The functions in `syncman` are not context bound yet.

**Comment by Jayesh333** [comment]
Okay. Let's complete it in `v0.14.0`
