### ISSUE TITLE
'http: Accept error: accept tcp [::]:4122: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by Martizs** [spaceuptech/space-cloud#503]
### Describe the bug
Hey guyz. I keep getting this error from time to time: 'http: Accept error: accept tcp [::]:4122: accept4: too many open files; retrying in 1s' and when it starts to appear it keeps repeating over and over. It happens seemingly randomly, after some time of space-cloud running(several days, few weeks) this error starts appearing and the frontend starts throwing 500 error codes in the console log. I know i've updated space-cloud last week, it was happening before the update as well(thought the update might fix it). Restarting space-cloud seems to fix it, but i'd like this not to happen at all. .So do you know what might be causing this, how to fix this? 
More about my space-cloud instance: 
1) Running space-cloud as a localhost on the server and proxying it via nginx.
2) I also have two periodic service functions set up to adjust values in the db.
3) Using space-cloud with React, so everything is javascript(typescript).
4)  Using mongodb
5) space-cloud 0.13.0
6) space-api 0.12.0

### Expected behaviour
It should run smoothly without any errors.

### Actual behaviour 
Seemingly at random starts throwing this error - 'http: Accept error: accept tcp [::]:4122: accept4: too many open files; retrying in 1s' and keeps repeatingly throwing it over and over. And the frontend gets 500 error codes in the console log when this starts, hence no data on the frontend.

### Steps to reproduce
Set up space-cloud instance as described and let it run for some time.

### Your environment
- Space Cloud version: 0.13.0
- OS: Ubuntu 16.04 xenial
- The client api version (if applicable): 0.12.0
- Browser (if applicable): all browsers

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
This seems like a bug due to requests which are stuck indefinitely. #502 will solve this

**Comment by YourTechBud** [comment]
Fixed in `v0.13.1`

**Comment by stephanoshadjipetrou** [comment]
hi @YourTechBud

Thanks for this!
Just a question, when is the v0.13.1 be released?

Thanks again!

**Comment by YourTechBud** [comment]
It should happen anytime today @stephanoshadjipetrou.

**Comment by YourTechBud** [comment]
Hey @stephanoshadjipetrou and @Martizs, `v0.13.1` is live now. Do comment on this thread if you encounter this bug again.

**Comment by stephanoshadjipetrou** [comment]
@YourTechBud the same error (as mentioned by @Martizs) appears even after updating space-cloud to 0.13.1. Does the usage of `api.Service` have to do anything with this?

**Comment by YourTechBud** [comment]
@stephanoshadjipetrou, `api.Service` has been removed in `0.13.0`. it's probably the reason you are seeing that bug. The functions module has been replaced by the `remote-services` module https://docs.spaceuptech.com/essentials/remote-services/
