### ISSUE TITLE
GraphQL upsert doesn't work as it claim

### ISSUE THREAD

**Issue by thienpow** [spaceuptech/space-cloud#512]
### Describe the bug

upsert suppose to insert a new record if no record found in the collection, but currently it works like update only.
`
mutation {
  update_pokemons(
    where: {_id: "2"},
    set: {
      name: "PikachuB",
      type: "Electric"
    }
  ) @mongo {
    status
  }
}
`

<img width="1103" alt="Screenshot 2019-11-19 at 2 25 32 PM" src="https://user-images.githubusercontent.com/9796623/69121942-77f54d80-0ad8-11ea-8935-1c39ed1dab72.png">

it shows success, but actually no record inserted.

**Comment by YourTechBud** [comment]
hey @thienpow. The correct query for upsert is
```graphql
mutation {
  update_pokemons(
    where: {_id: "1"},
    set: {
      name: "Pikachu",
      type: "Electric"
    },
    op: upsert
  ) @mongo {
    status
  }
}
```

Seems like the docs are incorrect.

**Comment by thienpow** [comment]
https://github.com/spaceuptech/space-docs/pull/13

**Comment by YourTechBud** [comment]
Fixed
