### ISSUE TITLE
Auto register Space Cloud with config stores

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#516]
### The problem faced currently?
Right now, in production mode, we have to register space cloud instances in the config store (eg: consul). It would be great if space cloud could register itself on init in the config store.

### How can we solve it?
Space Cloud should try to register itself with either the `NODE_ID` provided as environment variables/flag or an auto-generated `id` in the specified config store. If it could not register itself, it should exit the process.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Coming in `v0.15.0`
