### ISSUE TITLE
Dockerfile in the repo doesn't work as expected

### ISSUE THREAD

**Issue by takeerdevs** [spaceuptech/space-cloud#528]
### Describe the bug
issuing docker build command using Dockerfile included in this repo doesn't work out the box

### Steps to reproduce
clone repo and do docker build using existing Dockerfile

### Your environment
- Space Cloud version: 0.13.0
- OS: MacOs 10.15.1

**Comment by YourTechBud** [comment]
Fixed in `v0.16.0`
