### ISSUE TITLE
Overlapping content on blogs page

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#531]
### Describe the bug
![image](https://user-images.githubusercontent.com/24411676/70374128-98fdd100-1915-11ea-93a5-38ed8dcd4ea2.png)

### Your environment
- Browser (if applicable): Firefox version

**Comment by sharadregoti** [comment]
![image](https://user-images.githubusercontent.com/24411676/70374200-2ccf9d00-1916-11ea-9e53-c4b3bff2b896.png)

**Comment by Jayesh333** [comment]
Finished.
