### ISSUE TITLE
More tutorials and it should be in the docs.

### ISSUE THREAD

**Issue by vuhg** [spaceuptech/space-cloud#538]
### The problem faced currently?
The tutorial aren't clear and they are in the blogs, mean that i have to jump around and google.
That interrupts my learning experience as new comer.

Example: https://blog.spaceuptech.com/posts/getting-started-with-graphql-and-postgres/

### How can we solve it?
It would be great if i can actually build something small/simple with with `space-cloud` while reading tutorial without go/jump to other pages or websites.

**Comment by YourTechBud** [comment]
@Jayesh333 maybe we should update our learn page and link our getting started docs to learn?

**Comment by YourTechBud** [comment]
As decided, we are moving such tutorials to the Space Cloud Learn: https://learn.spaceuptech.com
