### ISSUE TITLE
Allow folder(s) to be auto created when uploading a file if the given path doesn't exists

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#54]
Should there be an options struct {upsertFolder: true} or should it be the default behavior?

**Comment by YourTechBud** [comment]
Write not overwriting the file is the default behaviour. We should, however, have an option to disable this perhaps?

**Comment by Jayesh333** [comment]
So shall we keep an options struct to turn this functionality on and off while the default behavior can be provided to the user by the client API by providing the intended default option?

**Comment by YourTechBud** [comment]
Let's do that!
