### ISSUE TITLE
Add support of distinct clause to queries

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#546]

**Comment by s-kris** [comment]
Can you add it to 0.15.3 ?

**Comment by Jayesh333** [comment]
Yes it's coming in `v0.15.3`!

**Comment by YourTechBud** [comment]
To be clear, @s-kris you can apply the distinct clause on a singl column only. This is a mongo db limitation

**Comment by s-kris** [comment]
Yes, understandable.
