### ISSUE TITLE
Security rule to prevent certain fields from being accessed

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#552]
### The problem faced currently?

Right now the security rules in Space Cloud does not allow to restrict access to certain **private** fields.

For example, in a food delivery app, we might want to restrict the access of the `address` field to only the user and the delivery man. This is currently not possible in Space Cloud without creating two separate table/collections. While we can definitely create separate tables/collections for a fresh app, but it might not be possible for an existing app.

This is a very common use case for many applications as discussed with @s-kris. Here's a solution that I thought of.

### How can we solve it?

Introduce a rule to remove certain fields from request or response.

**Rule specs:**

```json
{
  "rule": "remove",
  "fields": ["res.address", "res.phone_no"]
}
```

> **Note:** The above security rule will remove the `address` and `phone_no` fields from the response. In case `res` is an array of objects, Space Cloud should smartly remove the `address` and `phone_no` from each object in the `res` array.

A full-fledged example: Allow the address field in the `users` table to be queried only by the user himself or by the role `delivery_person`. The following will be the rule for the `read` operation of `users` table:

```json
{
  "rule": "and",
  "clauses": [
    {
      "rule": "match",
      "eval": "!=",
      "type": "string",
      "f1": "args.auth.id",
      "f2": "args.find.userId"
    },
    {
      "rule": "match",
      "eval": "!=",
      "type": "string",
      "f1": "args.auth.role",
      "f2": "delivery_person"
    },
    {
      "rule": "remove",
      "fields": ["res.address"]
    }
  ]
}
``` 

The above rule dictates that if the request for a user's details was not made by the user himself and if the role is also not the `delivery_person`, then the `address` field should be removed from the `res`. 

> Note: The `remove` rule always returns true in a `and`/`or` clauses array. 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We'll have to move the crud module inside the auth module. So external services won't be able to call the crud module directly. It will only be possible via the auth module.

While we are at it, @Jayesh333 can we add support to encrypt certain keys as well?

**Comment by Jayesh333** [comment]
Yeah, that will be an amazing addition! I am not sure though whether that will be a feature of the `schema` module or the `security` module. What do you think? @YourTechBud

**Comment by s-kris** [comment]
Thanks @Jayesh333 I think this feature will be a valued addition!

**Comment by YourTechBud** [comment]
Coming in `v0.15.0`
