### ISSUE TITLE
Security field to override request

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#553]
### The problem faced currently?

Currently, there are security rules to prevent a request under certain conditions. However, there is no way we can force or override a request by the user. 

For example, one might want the user to query only his todos. The current way to achieve this is:
```json
{
  "read": {
    "rule": "match",
    "eval": "==",
    "type": "string",
    "f1": "args.auth.id",
    "f2": "args.find.userId"
  }
}
```

However, this results in an authorized request in case the user specifies different `userId` or forgets to mention the `userId` at all. A better approach will be Space Cloud forcing/overriding the `userId` in the request to the database irrespective of what the user specifies.
 
### How can we solve it?

Introduce a security rule to force/override certain fields in a request.

**Example:** Override the `userId` field of the request:

```json
{
  "rule": "force",
  "field": "args.find.userId",
  "value": "args.auth.id"
}
```

The above field will set the `userId` field in the database query to the value of `args.auth.id` (UserId in the auth token). The `userId` field will be set even if the user doesn't specify it fom the frontend.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by s-kris** [comment]
This is good, I had experience with Firebase where the SDK does this and it can be used in the security rules. 
> The above field will set the userId field in the database query to the value of args.auth.id (UserId in the auth token). The userId field will be set even if the user doesn't specify it fom the frontend.

**Comment by YourTechBud** [comment]
Coming in `v0.15.0`
