### ISSUE TITLE
Ability to delete the current project

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#554]
### The problem faced currently?
There seems to be no way to delete the project. It'd be nice to delete the existing project and add new one from ui, given that the open-source version has a limit of 1 project per instance. 
### How can we solve it?
Trivial
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
coming in `v0.15.0`
