### ISSUE TITLE
Saved schema is missing for mongodb

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#565]
### Describe the bug
After creating a table with Schema, reloading the mission-control deletes the schema.
### Expected behaviour
Schema should be present after creating a table
### Actual behaviour 
Schema is missing (as seen on schema tab)
### Steps to reproduce
1. Install brand-new SC instance and setup mongodb
2. Create a new table with schema
3. Reload mission-control and see the schema for recently created table

### Your environment
- Space Cloud version: v0.13.1 [Deployed from here https://hub.docker.com/r/spaceuptech/space-cloud/ via CapRover]
- OS: Ubuntu 18.04 
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@s-kris can you try `v0.14.0` and see if the issue persists there as well?

**Comment by s-kris** [comment]
It seems to be fine in v0.14.0
Thank you
