### ISSUE TITLE
option to backup/restore schema/config/project/instance

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#566]
### The problem faced currently?
It is important to have a backup restore option either via download or to any cloud service.
Ironically I faced this #565 bug while thinking of this feature
### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
That's a really good point. @s-kris  Do you think a `Download Config` button to download the entire config as yaml will work?

Maybe @Jayesh333 can add this in `v0.15.0` itself

**Comment by s-kris** [comment]
Yes, it will :)

**Comment by Jayesh333** [comment]
Cool! We can add this in `v0.15.0` only then.

**Comment by Jayesh333** [comment]
Coming in `v0.15.0`. You will be able to export/import config of a particular project in json/yaml
