### ISSUE TITLE
delete project config

### ISSUE THREAD

**Issue by Saif-Ali-Kamal** [spaceuptech/space-cloud#568]
### Describe the bug
delete project config not deleting  the projects from config.yaml
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
We should fix this.

**Comment by Jayesh333** [comment]
coming in `v0.15.0`

**Comment by Jayesh333** [comment]
Seems as if this isn't solved yet.

**Comment by Jayesh333** [comment]
coming in `v0.15.0`
