### ISSUE TITLE
Need logging in Space Cloud

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#57]
Currently space cloud doesn't provide any logging. We need a proper logging mechanism with configurable levels.

**Comment by speshak** [comment]
Do you have any thoughts on what this might look like?  Should the log level be configurable via the config.yaml or as a CLI parameter?

**Comment by MichaelLeeHobbs** [comment]
Here is a sample Dockerfile

    FROM alpine:3.9
    WORKDIR /space-cloud
    RUN set -ex  \
      && apk add --no-cache ca-certificates unzip libc6-compat
    
    RUN wget https://spaceuptech.com/downloads/linux/space-cloud.zip -O space-cloud.zip
    RUN unzip space-cloud.zip \
        && rm space-cloud.zip \
        && chmod +x space-cloud
    
    COPY config.yaml .
    
    ENV PROD=false
    ENV PATH="/space-cloud:${PATH}"
    
    EXPOSE 8080
    CMD ./space-cloud run --config config.yaml

**Comment by MichaelLeeHobbs** [comment]
Go with an environment variable. Then when running in a container it would be easy to change on the fly without having to rebuild a container.

**Comment by YourTechBud** [comment]
@speshak and @MichaelLeeHobbs this is a tricky piece. The questions which comes to my mind is, whats the logging level? Where are the logs being published? In a file? Something like statsd or Prometheus?

Maybe we can start with simply logging to a file. Here we'll need the following inputs:
- Enable and disable logging
- Logging level
- File to flush the logs to

**Comment by MichaelLeeHobbs** [comment]
When doing something look for precedent, it will greatly increase the odds of being compatible with what already exists. 

For levels: https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm I always use these with one exception. I add an audit/security level to log anything that auditors or security related will need.

Where to send the logs? stdout. Then you can take advantage of Dockers logging.

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs I think we can use the logrus library. Let's give the user the option to decide where to send the logs (to a file or stdout). We can default to stdout for docker.

**Comment by MichaelLeeHobbs** [comment]
- Enable and disable logging
- Logging level
- File to flush the logs to
- Pluggable Logging endpoints: ElasticSearch, Syslog, etc

**Comment by MichaelLeeHobbs** [comment]
A note on ES per discord discussion. There are a few different ways ES can be auth'ed and they vary by the environment. Below is an AWS example as configured in fluentd.
```
<endpoint>
    url https://vpc-production-blue-ubj6n...xxi.us-gov-west-1.es.amazonaws.com
    region us-west-1
    access_key_id "AKIALB6.....MLSCJHQ"
    secret_access_key "hNvzshI.....sUf0oPG3EsvUdRc"
  </endpoint>
```

**Comment by YourTechBud** [comment]
Agreed. Lets break this issue down into smaller chucks. Maybe one ticket per module / package we have? Will make it easier to track and contribute. What say?

**Comment by ledex** [comment]
Even though this issue is pretty old I want to get started implementing the standardized logging for space-cloud. I would recommend using [logrus](https://github.com/sirupsen/logrus). 
This looks good on a first view and the logs are generated in JSON and can, therefore, be streamed easily to a centralized logging-and-monitoring-platform. What do you say @YourTechBud?

**Comment by YourTechBud** [comment]
Sounds perfect. @ledex i was thinking of making this as a module under the `utils` folder. The idea is to implement our own logger. This would be an interface. This will let us add something like elasticsearch in the future without having to change any SC code. Makes sense?

**Comment by ledex** [comment]
I see. Yeah, we should definitely do that, but I would still base this on the aforementioned logrus. Reimplementing the functionality of logrus doesn't make sense in my eyes.

I would suggest, that I make a proposal in the next few days and then we can improve it from there.

**Comment by YourTechBud** [comment]
Oh i guess i wasn't clear enough. Lets build it in a way to add implementations in the future. The first implementation will be logrus

**Comment by YourTechBud** [comment]
We have finally decided to use https://github.com/uber-go/zap. @sharadregoti is working on this right now.

**Comment by YourTechBud** [comment]
Coming in `v0.19.2`
