### ISSUE TITLE
UI Enhancements to mission control

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#570]
Kindly add Logout button in the header and a link to 'About' section in the sidebar. 
About section should include 
- current version of SC 
- underlying OS 
- one click copy of above info
- link to docs
- link to github
- link to discord 
- create a github issue link
- (optional) announcements 

These will be incredibly helpful to perform repetitive tasks straight from mission-control. 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
That's a great idea. We should definitely do this!

**Comment by YourTechBud** [comment]
@Jayesh333 let's break this down into smaller issues and close this one?

**Comment by Jayesh333** [comment]
Done. Coming in `v0.17.0`
