### ISSUE TITLE
Schema Inpection does not support @link directive 

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#571]
### Describe the bug
scheam inpector functionality in scheam module, will not add @link directive during reload scheam event if it is present in actual table.

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
This happens because fields with the `@link` directive are virtual, i.e. the database does not know about it at all.

**Comment by YourTechBud** [comment]
Closing this since nothing can be done about them
