### ISSUE TITLE
Bug in list directive functionality of GCP file storage module

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#572]
### Describe the bug
file storage moudle for gcp storage is not able to list files

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Is this solved in `v0.15.0`? @sharadregoti

**Comment by sharadregoti** [comment]
no

**Comment by YourTechBud** [comment]
Resolved in `v0.17.0`
