### ISSUE TITLE
Save the user-jwt token in explorer

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#574]
### The problem faced currently?
Inputted user token is not saved in Explorer and lost after navigation. 
It'd be helpful to have an option to test queries with multiple tokens to test authorization.

### How can we solve it?
Trivial

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
By multiple tokens here you mean the ability to switch between tokens with different claims for testing purpose and not multiple jwt secrets right?

If that's the case I have another suggestion. Maybe we can have a jwt token builder in explorer itself which let's you put claims in json. This way there is just a single token but it's value can be easily changed from the explorer itself. What do you think? @s-kris

**Comment by s-kris** [comment]
1. Correct. Multiple tokens for testing different claims and NOT different jwt secrets.

2. Jwt token builder will be awesome. It will be easier to use than generating the jwt token elsewhere and pasting in explorer. However if you think it's over engineering, just give us the good old text boxes to copy-paste :D

**Comment by Jayesh333** [comment]
Created a separate issue #575  for token builder. Let's keep this issue limited to persisting the jwt token as these two are separate tasks.

**Comment by YourTechBud** [comment]
@s-kris don't worry, @Jayesh333 will do anything to make your life easier! 🤣

**Comment by s-kris** [comment]
you are awesome guys haha!

**Comment by YourTechBud** [comment]
Coming in `v0.15.0`
