### ISSUE TITLE
Clear the saved jwt token (admin login) upon signature mismatch

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#576]
### Issue
Redeploying space-cloud on same domain causes signature mismatch issue upon login due to the previously saved jwt token in local storage (with a different password/secret)

### Temp Fix
Clear the old jwt token from local storage manually 

### Solution
Clear the saved jwt token from local storage via front-end upon signature mismatch error

**Comment by YourTechBud** [comment]
Just to confirm, @s-kris you are running space-cloud without the `--dev` flag right?

**Comment by s-kris** [comment]
@YourTechBud correct, without `--dev` flag.

**Comment by Jayesh333** [comment]
Apart from clearing the JWT token on signature mismatch, I think the Mission Control should also redirect to the login page right? @s-kris

**Comment by s-kris** [comment]
@Jayesh333 Yes! I saw that #340 is already in progress, you should be able to bind the functionality.

**Comment by Jayesh333** [comment]
Done. Coming in `v0.16.0`. Thanks @s-kris for bringing this up!
