### ISSUE TITLE
default rule isn't shown when creating new tables from sc-gui

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#585]
### Describe the bug
When we are adding a new table from space-cloud gui, default security rule isn't auto-filled. Instead the 'allow-all' rule is applied. 

### Expected behaviour
default security rule should be auto-filled for newly created table 
### Actual behaviour 
allow-all rule is auto-filled
### Steps to reproduce
1. Install & configure new sc-instance.
2. Create new project and add database (I was using mongodb)
3. Make the default security rule as 'deny-all'
3. Create a new table from sc-gui
4. You can see that 'allow-all' rule is auto-filled in rule section (in the modal)
### Your environment
- Space Cloud version: v0.14
- OS: Ubuntu 18.04 
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
As mentioned in #586, this should be fixed

**Comment by Jayesh333** [comment]
Fixed. coming in `v0.16.0`
