### ISSUE TITLE
default rule isn't applied to newly tracked tables 

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#586]
### Describe the bug
When we track a new table which was created outside of space-cloud gui (but in the same database), default security rule isn't applied to it. Instead the 'allow-all' rule is applied. 

### Expected behaviour
default security rule should be applied for newly tracked table 
### Actual behaviour 
allow-all rule is applied
### Steps to reproduce
1. Install & configure new sc-instance.
2. Create new project and add database (I was using mongodb)
3. Make the default security rule as 'deny-all'
3. Create a new collection from node-mongo sdk
4. Track it from sc-gui
5. You can go to rules tab and see that 'allow-all' rule is applied.

### Your environment
- Space Cloud version: v0.14
- OS: Ubuntu 18.04 
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@Jayesh333 this seems like an easy fix. Lets just make sure we upload the default security rule whenever a table is tracked.

Also, we should show the default security rule in the add table modal

**Comment by Jayesh333** [comment]
Yes, writing a detailed answer around these 3 related issues on a separate issue

**Comment by Jayesh333** [comment]
Fixed. coming in `v0.16.0`
