### ISSUE TITLE
add 'in' evaluater to security rule

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#587]
### The problem faced currently?
We need to use 'or' and write multiple clauses to compare a value with multiple options (for example to check if args.auth.role is in an array of values ['role1', 'role2', 'role3'])
### How can we solve it?
As talked on discord, 
```
rule: match
eval: in
type: string
f1: args.auth.rule
f2: [val1, val2, val3]
```
the above 'in' evaluator will be very helpful in writing efficient security rules

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
coming in `v0.15.0`
