### ISSUE TITLE
Error: provided db (mongo) does not exists

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#596]
not able to fetch data from graphiql even though database is configured correctly, connected and tables are tracked successfully. Same error for fresh installation and newly added tables too. 

### Your environment
- Space Cloud version: v0.15
>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Can you share your `config.yaml` and the graphql query that you are trying?

**Comment by s-kris** [comment]
config: https://github.com/spaceuptech/space-cloud/issues/597#issuecomment-569526343
graphql query: 
```
{
test @mongo{
        name  
        message
     }
}
```

**Comment by YourTechBud** [comment]
Hey @s-kris, have a look at the key inside the `modules.crud` object in your sc config. Assuming your key is `abc` you will use `@abc` in your graphql query.

In other words, use the `dbalias` to query not the `dbtype`. Makes sense?

**Comment by s-kris** [comment]
Ah, this is a breaking change from `0.14` to `0.15` ! Found the alias issue here: #488 
Thank you.
