### ISSUE TITLE
Do not reset the schema in case of error while saving it

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#605]
I was writing a lengthy schema for a table. After clicking `save` button, an alert popped-up with some error and the whole schema was replaced with previously saved schema, bad dx. Kindly fix it!

**Comment by Jayesh333** [comment]
This was solved in `v0.15.0`. Which one of these happened with you:

- Modal got closed automatically on error. When you clicked on edit the modal came back with the schema resetted to the previous schema
- Modal did not closed automatically on error. But you were able to see the latest schema you typed in. Then you closed it and opened it again to find the old schema.
- Modal did not closed automatically and the schema within the modal got replaced by the old one automatically without even closing the modal.

**Comment by s-kris** [comment]
This issue didn't happen in modal.
I was editing schema for existing table in schema tab

**Comment by Jayesh333** [comment]
Okay! Got it! This isn't solved. The modal getting closed automatically was solved in `v0.15.0`. Thanks for bringing this up!!

**Comment by YourTechBud** [comment]
Coming in `v0.15.3`
