### ISSUE TITLE
not able to save schema for existing tables

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#606]
### Describe the bug
When trying to add new schema to existing tables(no schema was given during creation), the save button is not enabled, it is in disabled state. (this happened long back during testing too in v0.14) 

### Expected behaviour
Save button becomes enabled after entering new text into schema textbox

### Actual behaviour 
Save button is in disabled state

### Steps to reproduce
1. Install sc.
2. Create a table without schema
3. Go to schema tab and add new schema

### Your environment
- Space Cloud version: v0.15
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Coming in `v0.15.3`
