### ISSUE TITLE
getting a graphql error for schema with field type:array when executing a mutation

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#607]
### Describe the bug
Mutation throws an error `invalid type received for field platforms in collection <collection_name>` when a schema is defined with a field of array type. 

### Your environment
- Space Cloud version: v0.15
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
coming in `v0.15.3`
