### ISSUE TITLE
Defining/editing Schema doesn't persist changes (Mysql DB)

### ISSUE THREAD

**Issue by meikibay** [spaceuptech/space-cloud#608]
### Describe the bug
When defining the Schema or updating it, the saved message is displayed but nothing happens within the data itself when querying and it doesn't persist those changes to the db as well (mysql in this case)

### Expected behaviour
Schema updates/created are saved and usable

### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Hey @meikibay! Thanks for bringing this to our notice.

Can you verify if the underlying table has been modified or not? You can check this directly with MySQL.

Also, lets say you add a column `foo` to a table. Now when you query this table, foo will still be `null` in the graphql response since no data has been inserted.

The best way to check if the schema is applied or not is by directly querying MySQL. You can use this query `describe table project_id.table_name`

**Comment by YourTechBud** [comment]
@meikibay can you confirm if the underlying table was updated?

**Comment by meikibay** [comment]
Hey @YourTechBud thanks for the fast reply...

The underlying table has not been modified and upon further investigation, creating a table with any sort of column is also not working for me...

So all in all I can't update schemas and can't create tables, but connections are fine, and querying still works too in the explorer...

**Comment by YourTechBud** [comment]
@meikibay Can you share the SC version and schema you are trying to create?

**Comment by meikibay** [comment]
Using "Latest" image with Docker-compose 

Even name: String isn't working:

![sampleschemaerror](https://user-images.githubusercontent.com/9073195/71767834-dd7a8d80-2f10-11ea-8e61-dda18284b6d2.png)

**Comment by YourTechBud** [comment]
@meikibay can you delete the space cloud image and container and restart the docker compose file? Maybe you can pin the space cloud version to `spaceuptech/space-cloud:v0.15.2` and try?

**Comment by meikibay** [comment]
That did solve it, thank you very much... but if you don't mind me asking, now I'm getting something "new" that the documentation doesn't really touch upon.

Queries coming in have a __typename added to them that are not resolving (requests times out), is this known? 

Thanks for your time really helped me a lot...

**Comment by YourTechBud** [comment]
`__typename` is a part of the GraphQL spec which is used for assisting client side caching. If you use a client side library like apollo, it will strip that off automatically. If you are querying manually via http, simply ignore it.

Glad things have started working for you. Do reach out on discord or here incase something pops up!

Closing this issue for now

**Comment by meikibay** [comment]
Great, thanks for the help
