### ISSUE TITLE
Docs doesn't specify that event trigger on database works only if the id field of table is specifed in find clause

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#612]
>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Done. Will be published along with `v0.17.0` release. Just to clarify, `id` field is not a compulsion. The primary or unique fields need to be specified in the `where` clause.
