### ISSUE TITLE
Default & auto id insertion doesn't work in update query

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#614]
### Describe the bug
during an update operation when id of type ID is not specified, SC doesn't automatically generate a new id as it does in insertion.
### Expected behaviour
if id is not provice & in scheam it is not null then during update operation. new id should be assigned automatically
### Actual behaviour 
getting error : pq: null value in column "id" violates not-null constraint]
### Steps to reproduce
perform an update operation without specifying value for ID type which is needed as specified in schema
### Your environment
- Space Cloud version: v0.15.2
- OS: linux
- The client api version (if applicable):
- Browser (if applicable): firfox
- Database: Postgres
>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Solved in `v0.15.3`

**Comment by YourTechBud** [comment]
This feature is causing the bug #619. Need to redo it.

**Comment by YourTechBud** [comment]
As discussed this id and default fields are applicable to insert operations only
