### ISSUE TITLE
Add support for regex in `utils/validate.go`

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#615]
We need this for reliable working of nested graphql and realtime queries

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Nested regex works in SC with Space API. However, in GraphQL we don't support a syntax yet I believe using which we can perform filtering on nested fields.

**Comment by YourTechBud** [comment]
For that you can pass the where clause as a variable. So even that use case is possible
