### ISSUE TITLE
GraphQL mutation doesn't return the value of the default fields

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#617]
### Describe the bug
Fields defined with `@default` directive do not return their value in the `returning` array while insert mutation.

### Expected behaviour
The `returning` array should return the value as it is inserted because of the `@default` directive

### Your environment
- Space Cloud version: 
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
coming in `v0.15.3`
