### ISSUE TITLE
Fields not defined in schema do not get inserted in mongo 

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#618]
Current scenario for schema in MongoDB:

If we do not mention schema, then the GraphQL inserts work in a schemaless fashion. However, if we do define schema then the GraphQL inserts work in a complete typed fashion. (i.e fields not defined in the schema do not get inserted).

Not sure if this is a bug or it should be like this only. Should MongoDB become completely type strict if a schema is defined or should we do type checking only for the fields defined in the schema but still allow inserts for undefined fields in the schema.

I believe the current behaviour is desirable otherwise people can corrupt the database by inserting a lot of fields into the document. So ideally if anyone is defining a schema then complete typed behaviour should be enforced or else completely schemaless behaviour should be enforced in case schema is not provided in my opinion.

Creating this issue to keep this discussion open and accommodate everyone's views on this.

**Comment by s-kris** [comment]
I wanted to discuss this. Provide a flag to merge the new field with the predefined schema before inserting into db.

**Comment by YourTechBud** [comment]
I think we should simply throw an error when something like this happens. The entire point of the schema is making sure your structure gets preserved.

**Comment by YourTechBud** [comment]
Coming in `v0.17.0`
