### ISSUE TITLE
Have a security rule to mask fields conditionally

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#621]
It would be be great if SC could conditionally encrypt / mask / hash certain fields before storing it in the database and unmask it automatically on retrieval.

Also, fields in the response should be maskable too.

We can use this to mask personally identifiable information like emails, name, etc. and for preventing testing and dev teams from viewing such information.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
What do you mean by masking the fields?

**Comment by YourTechBud** [comment]
Randomising it so it doesn't make sense.

**Comment by YourTechBud** [comment]
Resolved in v0.17.0
