### ISSUE TITLE
sort isn't working in queries 

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#622]
Sorting isn't working on queries, followed this: https://docs.spaceuptech.com/essentials/queries/sorting/

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Easy fix. Let's slide it in `0.15.3`. All we need to do is extract sort (and any other options we have added) here: https://github.com/spaceuptech/space-cloud/blob/master/utils/graphql/read.go#L111

@sharadregoti can you fix this?

**Comment by sharadregoti** [comment]
yep

**Comment by Jayesh333** [comment]
coming in `v0.15.3`
