### ISSUE TITLE
Add a data manager ui 

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#625]
A basic data editor GUI for connected database will be a great addition.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Finally got this done!! Coming in `v0.19.0`. It has a few limitations for Mongo though:
- Cannot insert/update a field of type array of objects
- For nested object in Mongo, the gui just provides a text area to type the son value of nested object
