### ISSUE TITLE
extract the raw token from incoming request and provide in args object

### ISSUE THREAD

**Issue by s-kris** [spaceuptech/space-cloud#627]
`args.req.token` can be used for multiple scenarios 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by sharadregoti** [comment]
it's already availabe as args.token

**Comment by YourTechBud** [comment]
We have now got it documented in several places including: https://docs.spaceuptech.com/security/security-rules/conditional-access/triggering-webhooks/#request-body
