### ISSUE TITLE
Let's break down the config file into smaller objects

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#667]
### The problem faced currently?
One huge config file can be overwhelming to edit and work with. People end up using `mission-control` exclusively because of this. This will make devOps practisely close to impossible with Space Cloud
### How can we solve it?
Lets break down the config file into smaller objects like what `kubernetes` does. Then we can have a `space-cli apply -f  /path/to/file` to apply all configuration to space-cloud.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This will help us solve #560.

**Comment by sharadregoti** [comment]
fixed in #884
