### ISSUE TITLE
GraphQL memory leak

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#678]
### Describe the bug
The `processQueryResult` method `utils/graphql/helpers.go` is not closing the wait group for `__typename` field. As a result, the query is waiting independently.

### Expected behaviour
wait group should be closed properly and the client should get a response in time

### Actual behaviour 
Client gets stuck in a pending state indefinitely

### Your environment
- Space Cloud version: `v0.15.3`

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Fixed in `v0.16.0`
