### ISSUE TITLE
error while creating config via Init command in Windows

### ISSUE THREAD

**Issue by atharva29** [spaceuptech/space-cloud#70]
Error thrown :- 
/d:\codeformer\space-cloud\space-cloud.yaml: The filename, directory name, or volume label syntax is incorrect.

**Comment by Jayesh333** [comment]
We need to try this on windows @YourTechBud

**Comment by Inconnu08** [comment]
@YourTechBud This is not a bug. It's working fine for me.

@atharva29 You have a typo on your file address. If you're using the whole drive address, it should start with the drive(volume) letter not with a `/`. So it should be:
`d:\codeformer\space-cloud\space-cloud.yaml`
assuming your config file is located there.

**Comment by YourTechBud** [comment]
Ah! Cool. So it works! Closing the issue now! @akshayjj1997 can you try this once to confirm?

**Comment by YourTechBud** [comment]
@Inconnu08 the bug exists. The default project name seems to be incorrect! So the init command works only if you change the project name! You think you can fix this?
