### ISSUE TITLE
Configurable image pull policy

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#702]
### The problem faced currently?

Right now, the image pull policy for the images deployed by user is hardcoded. However, I feel this control/choice should be given to the end user.

### How can we solve it?

Provide an option in the advanced tab of the deployments form to specify the image pull policy. Options that I know as of know are:

- Pull if not present locally
- Pull Always

We can default to Pull Always

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This is implemented in `runner`. Needs to be done on the frontend.

**Comment by Jayesh333** [comment]
Done. Coming in `v0.17.0`
