### ISSUE TITLE
Mention "enabling the realtime feature on each table" in docs for liveQuery feature

### ISSUE THREAD

**Issue by AmeyaDaddikar** [spaceuptech/space-cloud#704]
It is a very small thing, but it would be great if the docs mention in the live query section to enable realtime for the table on Mission Control. Websockets do not listen to changes in DB if the realtime option isn't enabled.

**Comment by Jayesh333** [comment]
Done. Will be published along with the `v0.17.0` release. Thanks for bringing this up! @AmeyaDaddikar
