### ISSUE TITLE
Getting error while calling list-collection in embedded database

### ISSUE THREAD

**Issue by Saif-Ali-Kamal** [spaceuptech/space-cloud#705]
### Describe the bug
1. Getting error while calling list-collection in embedded database 
2. Error in deleting table in embedded database 
3 Error in inserting data in embedded database

### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Done
