### ISSUE TITLE
Updating secrets doesn't update the service already using that secret

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#713]
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
We only need to do this for the `docker` driver. Kubernetes already does that for us

**Comment by YourTechBud** [comment]
Duplicate of #700
