### ISSUE TITLE
Gateway should mount config.yaml in volume for docker

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#714]
### Describe the bug
gateway container does'nt mount config.yml in docker volume so when the container is deleted the config also gets deleted
### Expected behaviour
config should have been saved even when the container gets deleted

### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment]
Will be fixed in #850

**Comment by YourTechBud** [comment]
Done
