### ISSUE TITLE
Add the ability to generate SQL views using the config.yaml file

### ISSUE THREAD

**Issue by AmeyaDaddikar** [spaceuptech/space-cloud#729]
Currently, we need to create the views manually when trying to re-create a Mission Control Database.

### How can we solve it?
If you can provide a UI Editor to run custom SQL queries from Mission Control itself, maybe you can then save these queries in your config.yaml file.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
This is possibly a duplicate of #493. Let's move the discussion to that thread. Thanks @AmeyaDaddikar for bringing this up!
