### ISSUE TITLE
CLI should work remotely for Docker setup

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#744]
Currently, the docker setup only works on a local machine. The `space-cli` setup command runs the gateway and runner containers and provides the secrets folder path and host file path to the runner container via environment variables. 

However, this docker setup works only on a local machine as of now, unlike Kubernetes which works remotely as well. It would be great if the Docker setup could also run remotely.

**Comment by YourTechBud** [comment]
Not needed anymore
