### ISSUE TITLE
Throw error on specifying unknown directives in the db schema

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#751]
Space Cloud does not throw an error even if we specify an unknown directive in the schema. 

For example, I specified a schema which had `createAt` directive instead of `createdAt` by mistake. I could only find out my mistake while querying the corresponding table. Instead, if space cloud could provide error while schema creation itself, development and debugging time could be saved by the developer

**Comment by sharadregoti** [comment]
fixed in #838
