### ISSUE TITLE
Allow the user to specify several tasks per service when using mission control

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#753]
### The problem faced currently?
Mission control doesn't let us specify multiple tasks in a single service.
### How can we solve it?
Allow the user to add tasks if she wishes to.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done! Coming in `v0.19.3`
