### ISSUE TITLE
MySQL returns 1/0 instead of true/false for Boolean values

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#758]
Mysql stores boolean value in the form of a single bit 1/0. There's no boolean type in MySQL.

However, we provide a unified API across all database and thus the user should be able to receive true/false for Boolean type fields while querying as it does in other databases. As of now, Space Cloud returns 1/0 to the user in case of MySQL for boolean fields. It should convert it into Boolean value before returning it to the user.

**Comment by YourTechBud** [comment]
This is possible now that we have post schema processing inside the `database` module.

**Comment by HeyItsJs** [comment]
I think this should be solved in `v0.19.0` itself. Note that this is a breaking change though.

**Comment by sharadregoti** [comment]
Fixed in #1050
