### ISSUE TITLE
Add a space-cli logs command

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#764]
### The problem faced currently?
Its hard to check the logs of the services deployed via space cloud. Makes it really hard to debug issues.
### How can we solve it?
Lets add a space-cli logs command. By default it will log all instances of a console (need to figure out how we can differentiate them). Users can optionally provide and index number, which will log that particular replica
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
The real question is how this will be done? Will we be using websockets to stream the logs back to the cli from the runner?

Here's how we get get the logs: https://stackoverflow.com/questions/53852530/how-to-get-logs-from-kubernetes-using-golang/53870271#53870271

**Comment by YourTechBud** [comment]
Done

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.0`
