### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#78]
### The problem faced right now
There's no way to enforce a schema for schemaless databases(like MongoDB) in SC.

### How can it be solved
Allow SC to accept a schema via Mission control for various collections. This schema should have the following field level config optons:
- Data type (int, string, bool etc)
- Default value
- Required
- Optional encryption / hash / bcrypt operation

**Comment by YourTechBud** [comment]
This will add another layer of security. We should probably add it for the v1 release.

**Comment by Jayesh333** [comment]
This can serve the #84, if we want the passwords to be hashed on back end.

**Comment by YourTechBud** [comment]
Coming in `v0.12.0`
