### ISSUE TITLE
Add mechanism to use most appropriate technologies for the given Cloud vendor

### ISSUE THREAD

**Issue by VedantParanjape** [spaceuptech/space-cloud#79]
Using NATS on Gcloud and Amazon's internal Service on AWS

**Comment by YourTechBud** [comment]
maybe we can add some functionality to the `space-cloud init` command to generate a config for a cloud provider? Something like `space-cloud init --cloud aws`?

We'll first have to add support for all those technologies. Lets make a list of mapping the tech we are using with the one these cloud vendors provide. We need to make sure they follow the same semantics though!

**Comment by YourTechBud** [comment]
@Jayesh333 should we put it for the v1.0.0 release?

**Comment by VedantParanjape** [comment]
@YourTechBud fair enough

**Comment by Jayesh333** [comment]
Additional technologies that we will need to support for different modules are:

1] **Real time** : 
- Kinesis (AWS)
- Azure Event Hub

2] **Functions**:
- Amazon MQ / Amazon simple notification service (SNS). Not sure which one to support.

3] **File storage**:
- Google cloud storage
- Azure blob storage

4] **CRUD**: 
- Dynamo DB (mongo equivalent for AWS)
- Google cloud data store (mongo equivalent for GCP)
- Cosmos DB (mongo equivalent for Azure)
- Azure SQL DB and Microsoft sql server

Add to this list, if anything is missing

**Comment by YourTechBud** [comment]
I don't think this is required anymore. We could always add new databases specific to cloud vendors.
