### ISSUE TITLE
Need a better way to manage file storage credential files

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#806]
### The problem faced currently?
GCS and S3 credentials files need to be mounted before we can actually start using the file storage module. This get a bit difficult to manage considering that the containers could already be running. 
### How can we solve it?
Mission control should accept the credentials file required by S3 and GCS. The gateway will be responsible for handling these files.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
@HeyItsJs lets close this if its tested

**Comment by HeyItsJs** [comment]
Done.
