### ISSUE TITLE
DB queries explorer

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#813]
Right now, in order to learn the syntax of GraphQL queries of Space Cloud, one has to go to docs, as there is no introspection available for GraphQL queries in Space Cloud. 

It would be great if we can have a query explorer, that shows examples of all the possible queries that can be made on a particular table along with a play button that executes that query in the graphiql tab

**Comment by Jayesh333** [comment]
Basic db queries explorer is implemented in `v0.17.0`. Keeping this issue open until we make it more feature-rich (like adding play button)

**Comment by HeyItsJs** [comment]
Done. Coming in `v0.19.0`
