### ISSUE TITLE
Add event queue function to space-api-js

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#823]

**Comment by sharadregoti** [comment]
we have to do the above for space-api-go

**Comment by Jayesh333** [comment]
This should come directly on the `API` object, right?

I have two alternative APIs for this in my mind. 
First alternative:
```js
const res = await api.queueEvent("event-type", {"foo": "bar"})
    .delay(0)
    .timestamp(new Date().getTime())
    .options({})
    .apply()
```
The `.apply()` method makes it consistent with the rest of the db functions. However, the `apply` method might give false indication that the event is triggered immediately.

Second alternative:
 ```js
const res = await api.event("event-type", {"foo": "bar"})
    .delay(0)
    .timestamp(new Date().getTime())
    .options({})
    .queue()
```

**Comment by YourTechBud** [comment]
@Jayesh333 close this if its done

**Comment by Jayesh333** [comment]
Done.
