### ISSUE TITLE
insecure connection between server and client

### ISSUE THREAD

**Issue by VedantParanjape** [spaceuptech/space-cloud#83]
SSL absent, no provision to transfer data in a secure manner

**Comment by YourTechBud** [comment]
You would usually have a load balancer or a reverse proxy like Nginx which would terminate the SSL. But we could have SSL/TLS support in golang directly for the http, and grpc servers.

**Comment by VedantParanjape** [comment]
yes, it should be built into the bones, not some exterior layers providing security

**Comment by YourTechBud** [comment]
Makes sense. It's an easy one. Should i assign this issue to you?

**Comment by VedantParanjape** [comment]
Sure, i can do this.
