### ISSUE TITLE
removing primary key from schema gives error for postgres

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#831]
### Describe the bug
current shema
type clusters {
  cluster_id: ID! @primary
  project_id : ID
	user_id : ID!
	type : ID!
  url : String!
}
scheam after removing primary key
type clusters {
  cluster_id: ID!
  project_id : ID
	user_id : ID!
	type : ID!
  url : String!
}
the table is empty
got error
{"error":"pq: constraint \"c_clusters_cluster_id\" of relation \"clusters\" does not exist"}
### Your environment
- Space Cloud version: v0.17.0
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Does this work for `mysql`?

**Comment by sharadregoti** [comment]
fixed in #838
