### ISSUE TITLE
creating event through mission control doesn't create event according to the config provided

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#832]
### Describe the bug
creating eventing with retires & timeout > 0 doesn't get reflected to config.yaml file
that's why after reload it show both the field as zero
even though the field were set to some value
& creating event doesn't fill the name field of event object in config.yaml
after refresh name is blank

Mission control version : v0.17.0
- Space Cloud version: v0.17.0
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by Jayesh333** [comment]
Hey @sharadregoti, is Mission Control giving wrong values to Space Cloud while creating an event trigger or is it a problem with the gateway?

**Comment by YourTechBud** [comment]
@Jayesh333 is this a frontend or backend problem?

**Comment by sharadregoti** [comment]
I didn't checked the inspector tab of browser. So i don't know if it's a backend or frontend problem.

**Comment by Jayesh333** [comment]
Hey @sharadregoti, can you confirm if this bug still exists. I was unable to reproduce this bug.

**Comment by sharadregoti** [comment]
@Jayesh333 The bug has been fixed in v0.17.0 by shubaham
