### ISSUE TITLE
unsafe password handling

### ISSUE THREAD

**Issue by VedantParanjape** [spaceuptech/space-cloud#84]
actual plaintext passwords being sent in user management, really unsafe thing to do. Standard way is to salt the passwords and the compare the hashes, not plain text passwords

**Comment by YourTechBud** [comment]
We can add this feature to the user management module. Open to contributions for this one.

**Comment by Jayesh333** [comment]
The hashing will be performed on the back end right? Or should the front end send hashed passwords to space cloud directly?

**Comment by Jayesh333** [comment]
This might be solved by #78

**Comment by VedantParanjape** [comment]
https://stackoverflow.com/questions/3391242/should-i-hash-the-password-before-sending-it-to-the-server-side

**Comment by VedantParanjape** [comment]
@Jayesh333 no, as soon as we take a password from client, we convert it into a key, then hash the key, and preferably transfer it using encrypted connection.

**Comment by YourTechBud** [comment]
Just hash the password in the client library. Let the server store it as is

**Comment by ollykel** [comment]
> Just hash the password in the client library. Let the server store it as is

NEVER DO THIS. The hash effectively becomes the password, and anyone who manages to access the users table will be able to use the hash to log in. With server-side hashing the hacker still needs to know the original password to log in.

Always handle hashing + salting (and really, any security-critical business logic) server side, where you have complete control over the process.

**Comment by YourTechBud** [comment]
Makes sense. There is no easy way out on this one.

**Comment by ledex** [comment]
@YourTechBud I think this issue can be closed. It has been solved in #182

**Comment by YourTechBud** [comment]
Will close it once `v0.8.0` is merged in master. Not sure how it should work though! It is fixed, but it isn't live yet

**Comment by ledex** [comment]
Okay. But now it seems that there is still something to do. I would add a tag "v0.8.0" to this issue and close it.

**Comment by YourTechBud** [comment]
Done
