### ISSUE TITLE
Restarting docker causes space-cloud containers to not work anymore

### ISSUE THREAD

**Issue by AmeyaDaddikar** [spaceuptech/space-cloud#852]
The frst time I setup my local space-cloud environment, I closed docker down docker as it was eating my machine's resources. Later on when I started it again, stuff started to break and had to rebuild my entire space-cloud + DB environment again.

Apparently, in the tutorial, it says to use the 
`docker inspect` Command to get the IP of the DB we use. However, I suppose this IP is volatile, and upon relaunching docker, new IPs are assigned to docker.

**Comment by AmeyaDaddikar** [comment]
What if for the initial setup, there would be an option to deploy a DB container first alongside giving the DB url? That way space-cloud can manage the local DB as well

**Comment by YourTechBud** [comment]
Coming in v0.17.0
