### ISSUE TITLE
Add support for inserting docker registry in mission control

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#862]
Need to add a `dockerRegistry` field in mission-control in the project setting. Mission control needs to take the format the docker registry string based on the hosted cloud vendor. Its mostly in the following format: `domain.com/project-id`.
Let's try and do it for the following vendors
- Docker hub
- GCP
- AWS
- Microsoft Azure
- DigitalOcean

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by Jayesh333** [comment]
Done. Coming in `v0.17.0`
