### ISSUE TITLE
Document procedure to use the gateway binary directly

### ISSUE THREAD

**Issue by akhedrane** [spaceuptech/space-cloud#873]
### The problem faced currently?
In some environment we can't use docker, so we need native binary file to use with hashicorp/nomad

### How can we solve it?
By keeping the old containerless deployment way.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Can you specify which features of SpaceCloud you are interested in or use?

**Comment by akhedrane** [comment]
> Can you specify which features of SpaceCloud you are interested in or use?

All of them.

**Comment by YourTechBud** [comment]
There will be a couple of features unavailable if you are using the binaries directly. These features will be affected:
- deployments and autoscaling
- secret mangement for services
- service routing

Does that work for you?

**Comment by akhedrane** [comment]
> There will be a couple of features unavailable if you are using the binaries directly. These features will be affected:
> 
> * deployments and autoscaling (**Nomad**)
> * secret mangement for services (**Vault**)
> * service routing (**Traefik**)
> 
> Does that work for you?

they'll be managed outside space-cloud.

**Comment by YourTechBud** [comment]
Awesome. I think we can ship out a binary for `gateway`. Thats the same as the old space cloud.

You can build the gateway folder in this repo to get your own binary. You think that would work for you?

**Comment by akhedrane** [comment]
i've to test it.

**Comment by YourTechBud** [comment]
I'll add the build from source instructions along with how to use it in our docs. Sounds fair?

**Comment by akhedrane** [comment]
fair enough. thank you.

**Comment by YourTechBud** [comment]
The documentation can be found here: https://docs.spaceuptech.com/install/using-gateway-directly/
