### ISSUE TITLE
File store edit connection button show wrong ui for amazon s3

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#879]
### Describe the bug
i have seleted s3 as file store.
but when i want to edit connection details, it shows wrong ui. It shows ui for local store instead of amazon s3 store.
![image](https://user-images.githubusercontent.com/24411676/77231432-dc2c3900-6bc0-11ea-95c8-a7721874e6b4.png)

**Comment by Jayesh333** [comment]
Fixed in `v0.17.0`
