### ISSUE TITLE
Return error, when I using the regex based search

### ISSUE THREAD

**Issue by Barretem** [spaceuptech/space-cloud#885]
### Describe the bug
When I use the following regex to make an case insensitive search in mysql DB. It doesn't work. The graphql words just like this:
`
query {
  pokemons(
    where: { description: { _regex: "(?i)strong"}}
  ) @mysql {
    _id
    name
  }
}
`
### Expected behaviour
The error returned is as follows：
`
"graphQLErrors": [
    {
      "message": "Error 1139: Got error 'repetition-operator operand invalid' from regexp"
    }
  ]
`
### Your environment
- Space Cloud version: v0.16.0
- DB: mysql

**Comment by YourTechBud** [comment]
cc @Jayesh333 
I believe its something about using special regex or something of that sort.

**Comment by Jayesh333** [comment]
Hey @Barretem, this query is working for me. Which version of MySQL are you using?

**Comment by Jayesh333** [comment]
Hey @Barretem. Closing this issue as it seems to be working fine. Feel free to re-open or comment on this issue with more context about the bug if it still exists. Will be more than happy to help.
