### ISSUE TITLE
Variables are ignored in GraphQL subscriptions

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#907]
### Describe the bug
The query variables sent in the request for GraphQL subscription over WebSockets are ignored. If we specify some variables in the GraphQL query of subscription, then we get this error - `Scope not present`

### Expected behaviour
The GraphQL query variables should be used by Space Cloud.

### Actual behaviour 
Space Cloud gives an error

### Your environment
- Space Cloud version: `v0.17.0`

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Coming in `v0.17.0`
