### ISSUE TITLE
Apollo client gives error in realtime subscriptions when using delete mutation

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#917]
While using apollo client for realtime subscriptions with space cloud I receive the following error - https://github.com/apollographql/apollo-client/issues/2510 

My GraphQL subscription query:
```graphql
subscription {
  todos(where: {userId: {_eq: "${this.userId}"}}) @mydb{
    type
    payload {
      _id
      value
      isCompleted
      userId
    }
  }
}
```

I get this error only on delete mutation. I believe that it's because the payload contains `_id` during inserts but not during deletes. 

**Solution:** We can fix this by sending the fields within the `find` clause in the `payload` during delete mutation.

**Comment by YourTechBud** [comment]
I've fixed it, @Jayesh333 you'll have to confirm if it works

**Comment by Jayesh333** [comment]
It works. Closing this issue. Coming in `v0.17.0`
