### ISSUE TITLE
Return error field as null instead of undefined in GraphQL mutations

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#919]
Right now, if I want to perform GraphQL mutations with error handling, then I have to write queries like this:
```graphql
mutation {
  delete_todos (where: $where) @mydb {
    status
    error
  }
}
```

Note that I have to select `error` as well in the GraphQL query. When there is no error in the mutation, Space Cloud sends `error` as undefined. While this is perfectly alright, but the ReactDevTools give me a warning like this:
```
react_devtools_backend.js:6 Missing field error in {
  "returning": null,
  "status": 200
}
``` 

I think this warning can be prevented by sending null instead of undefined

**Comment by YourTechBud** [comment]
In go there is no concept of `null` or `undefined`. The only way out is not sending error at all, but that seems incorrect.

**Comment by Jayesh333** [comment]
If there's no concept of null, then how am I getting `null` for the `returning` field. 

If I make the following query:
```graphql
mutation {
  update_todos(where: {_id: {_eq: $todoId}}, set: {isCompleted: $isCompleted}) @mydb {
    status
    error
    returning
  }
}
```

In the above case I get the following warning:
```
react_devtools_backend.js:6 Missing field error in {
  "returning": null,
  "status": 200
}
```

To confirm I also checked the network tab and I saw that I am getting the `returning` field as `null`. So we should be able to send the same value for `error` as well I feel.

**Comment by Jayesh333** [comment]
Done. Coming in `v0.17.0`
