### ISSUE TITLE
Send error on invalid unsubscribe request

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#920]
Right now, if we send an invalid subscribe request (request without `dbType`) via `space-api-js`, then Space Cloud sends an ack `true` even though it did not find any such subscription object. This gives a false indication that unsubscribe operation was successful even though it was not. Sending an invalid subscribe request is a bug of client API. However, Space Cloud should send error on such invalid requests rather than silently ignoring such errors and sending positive ack so that such problems can be detected and solved earlier.

**Comment by YourTechBud** [comment]
Done
