### ISSUE TITLE
Invalid graphql message type for subscriptions 

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#921]
### Describe the bug
While using Apollo GraphQL subscriptions with Space Cloud, Space Cloud sends a message with type `stop` whenever it receives a message with type `stop` from the client. However, `stop` messages should only be sent from client to server and not the other way around. Hence Apollo client throws this error - `Invalid message type`
 
### Expected behaviour
Space Cloud shouldn't send a message with type `stop` to the client. 

### Actual behaviour  
Space Cloud sends a message with the type `stop`.

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Done. Sending `complete` instead. Not sure if thats right though. @Jayesh333 you'll have to confirm.

**Comment by Jayesh333** [comment]
Instead of `complete`, it's sending the `error` message as such: 

```json
{
  "payload": {
    "authToken": "",
    "variables": null,
    "error": [
      {
        "message": "no subscription found on db () and col (todos)"
      }
    ]
  },
  "id": "1",
  "type": "error"
}
```

Note, how the `db()` is empty in the `message`. I think its because the stop message might be expecting `dbType/dbAlias` but it's not getting that. (Apollo sends `stop` message on its own whenever it gets `error` on `start` message)

**Comment by Jayesh333** [comment]
Done.  Coming in `v0.17.0`.
