### ISSUE TITLE
Token in Apollo websocket requests gets ignored 

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#922]
Right now the recommended way of setting the token while initializing the WebSocket link of apollo client is like this:

```js
 const wsLink = new WebSocketLink({
    uri: websocketURL,
    options: {
      reconnect: true,
      connectionParams: {
        authToken: "<token-value>"
      }
    }
  });
```

On doing this, the apollo client sends the token value in the `payload.authToken` field of the `connection_init` message. However, Space Cloud expects the token value in `payload.connectionParams.token`. That's why the subscription remains unauthorized.

**Comment by YourTechBud** [comment]
Not relevant since we'll use the token provided in the `start` message
