### ISSUE TITLE
How to count the amount of table's data for graphql?

### ISSUE THREAD

**Issue by shaowin16** [spaceuptech/space-cloud#933]

**Comment by YourTechBud** [comment]
This feature isn't supported in the GraphQL layer.

@Jayesh333 maybe we can add a `count_tablename` prefix to the fields to trigger a count query. This would mean no table could start with a prefix of count though

**Comment by shaowin16** [comment]
> This feature isn't supported in the GraphQL layer.
> 
> @Jayesh333 maybe we can add a `count_tablename` prefix to the fields to trigger a count query. This would mean no table could start with a prefix of count though

When will this feature be launched？

**Comment by Jayesh333** [comment]
Hey @shaowin16 I have laid ou the specs for aggregations in general (includes count as well) - https://github.com/spaceuptech/space-cloud/issues/939. It will be great if you can contribute with your feedback/ideas :smile:

**Comment by YourTechBud** [comment]
The goal is to get this out within the next 5, weeks. We can expedite it if you need it urgently @shaowin16

**Comment by YourTechBud** [comment]
Closing since its covered in #939
