### ISSUE TITLE
Aggregations support in Space Cloud

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#939]
Right now in order to perform aggregations on data, we need to create views. However, aggregations are such a common use case that I believe Space Cloud should support it out of the box via its GraphQL API.

Notable aggregations that we need to support:
- `count`
- `sum`
- `min`
- `max`
- `avg`

I have two alternate approaches  in my mind for providing aggregations which are as follows:

## Alternate 1 (Using an `aggregate` field)
Syntax:
```graphql
query {
  <table> (where: $where, group: $groupByArray, sort: $sortArray}) @db {
    ...fields
    aggregate {
      count
      sum {
        ...fields
      }
      avg {
        ...fields
      }
      min {
        ...fields
      }
      max {
        ...fields
      }    
    }
  }
} 
``` 

### Example: Count the number of users by age living in India:

```graphql
query {
  users(where: {country: "India", group: ["age"]}) @mydb {
    age
    aggregate {
      count
    }
  }
} 
``` 

### Example: Calculate total, min and max expenditures of an user in various categories like travelling, food, etc.:

```graphql
query {
  expenditures(where: {userId: $userId, group: ["category"]}) @mydb {
    category
    aggregate {
      sum {
        amount
      }
      min {
        amount
      }
      max {
        amount
      }
    }
  }
} 
``` 

## Alternate 2 (Using  aggregation directives)
Syntax:
```graphql
query {
  <table> (where: $where, group: $groupByArray, sort: $sortArray}) @db {
    ...fields
    <any-name> @count
    <any-name> @sum(field: "<field-name>")
    <any-name> @avg(field: "<field-name>")
    <any-name> @min(field: "<field-name>")
    <any-name> @max(field: "<field-name>")
  }
} 
``` 

### Example

```graphql
query {
  expenditures(where: {userId: $userId, group: ["category"]}) @mydb {
    category
    totalAmount @sum(field: "amount")
    maxAmount @min(field: "amount")
    minAmount @max(field: "amount")
  }
} 
``` 

## Comparing both the approaches

Personally I like both the approaches and I am comfortable with any of the above. Here are some pros and cons for both that I could think of:

- In the first alternative, the table/collection should not have a field named `aggregate`. Chances are very less though that a field will be named `aggregate`. To further reduce the chances we can use the `aggregate_fields` keyword instead of `aggregate`. The alternative, however, completely eliminates the possibility of collisions.
- In the second alternative, however, the user can face a dilemma while deciding the name of the field in the GraphQL query. (It's a common habit to overthink about the naming conventions🙈)
- In a big table where we might want to sum tens of different fields (common in ERP apps or accounting/financial apps), it might be tedious to write the aggregation directives again and again in the second alternative.
- In the first alternative, the fields required by the user are nested inside the `aggregate` object. This means the user might have to map this data on frontend if he wanted a flat structure. Don't find this a big problem personally though.  

Overall I feel that the first approach is better because it is more explicit about the fact that we are performing aggregations and because of points 2 and 3 in the above comparison. Also, I feel the first approach should be easy to implement than the second approach.

## Voting
> For the first alternative, give this message a :rocket: and for the second alternative give a :heart:. If you have any other alternatives as well, comment them below. 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by pandaxxt** [comment]
We have the same requirement, same the implement in the Hasura, https://hasura.io/docs/1.0/graphql/manual/queries/aggregation-queries.html

**Comment by YourTechBud** [comment]
This is finally done!! Coming in `v0.18.0`.
