### ISSUE TITLE
Allow the developer to specify error messages in security rule

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#961]
### The problem faced currently?
Currently the security error messages are not in the user's control
### How can we solve it?
Allow user to provide error message in each security rule. For aggregation rules (which contain sub rule(s) - e.g. `and`, `or`), the error message of the child clause should be returned (existing behaviour) if the error message is not defined.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done in `v0.18.0`
