### ISSUE TITLE
Sql server cannot have more than 1 timestamp column

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#969]
### Describe the bug
While creating a new project gateway create 2 tables in selected database. Event logs & Invocation logs.
Event logs has more than 1 column whose type is timestamp
But sql server can only have 1 coulmn with type timestamp. 
while creatin project it throws error
**{"error":"mssql: A table can only have one timestamp column. Because table 'event_logs' already has one, the column 'event_ts' cannot be added."}**

### Expected behaviour
It should create table successfully
### Steps to reproduce
create a new space cloud project & select database sql server

This might help:
https://stackoverflow.com/questions/12063850/multiple-timestamp-columns-in-sql-server-2000
### Your environment
- Space Cloud version:
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
The problem is that SC is using and deprecated data type. We should instead use the recommended data type fro storing date times

**Comment by YourTechBud** [comment]
Fixed
