### ISSUE TITLE
Tracking existing table

### ISSUE THREAD

**Issue by sharadregoti** [spaceuptech/space-cloud#978]
In docs, add a new page "tracking existing table"
Explain the tracking procedure & what can be tracked
1) for sql databases any type varchar(any size) will be considered as ID type in gateway
2) for automatically detecting index, index name should start with index keyword
if above is not met
2 ways to solve it
1) drop all the index directly form database shell, and create indexes through misson control
2) rename indexs by running the sql queries (sql queries will be mentioned in docs)

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by HeyItsJs** [comment]
Done. Explained the method of tracking tables. Also mentioned about the limitation of index tracking and the workarounds. Didn't mention the first point though (Any type varchar will be considered as ID).
