### ISSUE TITLE
All space-cli getters throws weird errors if project flag isn't provided

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-cloud#989]
Running `space-cli get <>` without the `--project` flag throws unpredictable errors. We should have a function called `getProjectID()` which returns the projectID and a boolean (specifying if the projectID) exists are not. This function will attempt to get the projectId from viper.
All getters can call this function and check if the projectId has been provided

**Comment by sharadregoti** [comment]
is there a way in viper to make the flag as **required** compulsory

**Comment by YourTechBud** [comment]
We cannot make this flag required since its a persistent flag
