### ISSUE TITLE
Untrack a tracked table

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#997]
### The problem faced currently?
Currently, the user can't untrack a tracked table. 

This means if the user wants some table to exist but not be exposed via Space Cloud's API, he would have to either configure the security rules of that table or change the default security rules. 

This can be annoying especially if there are lots of such tables and he doesn't want to change the default security rules.
 
### How can we solve it?
Provide an option to untrack a table so that the user can simply disable any API access to it while keeping the table at the same time. This untrack option will simply remove the table from Space Cloud's config and will be listed in the untracked tables from where it can be tracked again.   

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by sharadregoti** [comment]
fixed in #1033
