### ISSUE TITLE
Delete an untracked table

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#998]
### The problem faced currently?
No option to delete an untracked table. This means in order to remove unnecessary untracked tables, we first have to track them and then delete them. This is very annoying.

### How can we solve it?
Provide an option to delete an untracked table via Mission Control. The same API that is used for deleting a tracked table can be used to delete an untracked table as well. So no need to make an extra API.
 
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by sharadregoti** [comment]
Already supported feature
